(()=>{
 const params=new URLSearchParams(location.search),token=params.get('token'),demo=params.get('demo')==='1',mode=params.get('mode')==='active'?'active':'alert',demoStyle=['harmful','beneficial','neutral'].includes(params.get('style'))?params.get('style'):'neutral',alertFilter=['harmful','beneficial'].includes(params.get('filter'))?params.get('filter'):'',stage=document.getElementById('bitsAlertStage'),dock=document.getElementById('bitsActiveDock'),queue=[];
 let showing=false,cursor=null,sound=true,active=[],offset=0,rotateTimer=null,audioCtx=null,timersPaused=false,resolvedAt=0,resolvedSounds={harmful:'',beneficial:''};
 const recordedAudioFiles={
  harmful:[
   '../assets/audio/bits-harmful-v5.part00.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part01a.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part01b.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part01c.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part02.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part03a.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part03b.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part03c.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part04.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part05.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part06.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part07.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part08a.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part08b.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part08c.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part09.b64?v=20260930-4',
   '../assets/audio/bits-harmful-v5.part10.b64?v=20260930-4'
  ],
  beneficial:Array.from({length:7},(_,i)=>`../assets/audio/bits-beneficial-v4.part${String(i).padStart(2,'0')}.b64?v=20260929-7`)
 },recordedAudioUrls=new Map(),playingAudio=new Set();
 document.body.dataset.mode=mode;
 const imageUrl=value=>{try{const u=new URL(value,location.href);return u.origin===location.origin&&/\.png$/i.test(u.pathname)?u.href:''}catch{return''}};
 const secondsLabel=seconds=>{const total=Math.max(0,Math.ceil(Number(seconds)||0)),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;if(h)return`${h}H ${String(m).padStart(2,'0')}M`;if(m)return`${m}M ${String(s).padStart(2,'0')}S`;return`${s}S`};
 const remaining=item=>{if(!item.expires_at)return'HASTA ELIMINAR';if(timersPaused&&item.paused_remaining_seconds!==null&&item.paused_remaining_seconds!==undefined)return'PAUSADA · '+secondsLabel(item.paused_remaining_seconds);const ms=Date.parse(item.expires_at)-Date.now();if(ms<=0)return'FINALIZADA';return secondsLabel(ms/1000)};
 function context(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();return audioCtx}
 function tone(ctx,{frequency=220,to=frequency,duration=.4,start=0,type='sine',gain=.16}){const osc=ctx.createOscillator(),g=ctx.createGain(),when=ctx.currentTime+start;osc.type=type;osc.frequency.setValueAtTime(frequency,when);osc.frequency.exponentialRampToValueAtTime(Math.max(20,to),when+duration);g.gain.setValueAtTime(.0001,when);g.gain.exponentialRampToValueAtTime(gain,when+.025);g.gain.exponentialRampToValueAtTime(.0001,when+duration);osc.connect(g).connect(ctx.destination);osc.start(when);osc.stop(when+duration+.03)}
 function base64ToBlobUrl(text,mime='audio/ogg'){const clean=String(text||'').replace(/\s+/g,''),binary=atob(clean),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return URL.createObjectURL(new Blob([bytes],{type:mime}))}
 async function defaultAudioUrl(style){if(recordedAudioUrls.has(style))return recordedAudioUrls.get(style);const files=recordedAudioFiles[style];if(!Array.isArray(files)||!files.length)return'';const responses=await Promise.all(files.map(path=>fetch(path,{cache:'no-store'})));if(responses.some(r=>!r.ok))throw new Error('No se pudo cargar el audio de alerta.');const parts=await Promise.all(responses.map(r=>r.text()));const url=base64ToBlobUrl(parts.join(''),'audio/ogg');recordedAudioUrls.set(style,url);return url}
 async function resolveCustomSounds(force=false){if(!token||demo||!window.SANLEAN_SUPABASE?.url)return resolvedSounds;if(!force&&Date.now()-resolvedAt<2500)return resolvedSounds;try{const r=await fetch(window.SANLEAN_SUPABASE.url+'/functions/v1/stream-bits-sounds/resolve?token='+encodeURIComponent(token),{cache:'no-store',signal:AbortSignal.timeout(7000)});if(r.ok){const data=await r.json();resolvedSounds={harmful:data.harmful||'',beneficial:data.beneficial||''}}}catch{}resolvedAt=Date.now();return resolvedSounds}
 function registerAudio(audio){playingAudio.add(audio);const cleanup=()=>playingAudio.delete(audio);audio.addEventListener('ended',cleanup,{once:true});audio.addEventListener('error',cleanup,{once:true});return audio}
 async function playRecordedSound(style){await resolveCustomSounds(true);const custom=resolvedSounds[style]||'',src=custom?custom+(custom.includes('?')?'&':'?')+'v='+Date.now():await defaultAudioUrl(style);if(!src||!sound)return false;const audio=registerAudio(new Audio(src));audio.preload='auto';audio.volume=1;await audio.play();return true}
 async function playSound(style){if(!sound)return;if(style==='harmful'||style==='beneficial'){try{await playRecordedSound(style)}catch{}return}try{const ctx=context();ctx.resume?.();tone(ctx,{frequency:220,to:150,duration:.42,type:'triangle',gain:.12});tone(ctx,{frequency:330,to:260,duration:.35,start:.12,type:'sine',gain:.08})}catch{}}
 function diamond(src,className=''){const frame=document.createElement('div');frame.className=('bits-perk-diamond '+className).trim();frame.setAttribute('aria-hidden','true');const img=document.createElement('img');img.src=src;img.alt='';frame.appendChild(img);return frame}
 const particleSlots=[[5,18],[14,8],[27,22],[39,11],[52,24],[65,9],[78,20],[91,12],[9,42],[24,35],[41,47],[58,38],[76,45],[94,34],[6,67],[19,78],[35,63],[54,74],[70,60],[86,76],[96,64]];
 function addParticles(host,item,style){const src=imageUrl(item.image);if(!src)return;const count=style==='neutral'?17:21,opacities=[1,.96,.90,.82,.74,.88,.98,.79,.93,.86],scales=[.72,.86,1.02,.78,.94,1.08,.82,.98,.76,1.04];particleSlots.slice(0,count).forEach(([x,y],i)=>{const frame=diamond(src,'bits-alert-particle'),jitterX=((i*37)%9)-4,jitterY=((i*23)%9)-4,scale=scales[i%scales.length],rotation=-28+((i*31)%57),mostlyFixed=i%4===0,medium=!mostlyFixed&&i%3===0,dirX=i%2?-1:1,dirY=i%3===0?-1:1,motion=mostlyFixed?.18:medium?.52:.88,dx=Math.round(dirX*(34+((i*17)%105))*motion),dy=Math.round(dirY*(24+((i*29)%80))*motion),dx2=Math.round(-dirX*(18+((i*13)%72))*motion),dy2=Math.round((i%2?-1:1)*(16+((i*19)%62))*motion),opacity=opacities[i%opacities.length];frame.style.setProperty('--x',`${x+jitterX}vw`);frame.style.setProperty('--y',`${y+jitterY}vh`);frame.style.setProperty('--r',`${rotation}deg`);frame.style.setProperty('--s',String(scale));frame.style.setProperty('--op',String(opacity));frame.style.setProperty('--delay',`${((i*7)%11)*.045}s`);frame.style.setProperty('--dx',`${dx}px`);frame.style.setProperty('--dy',`${dy}px`);frame.style.setProperty('--dx2',`${dx2}px`);frame.style.setProperty('--dy2',`${dy2}px`);frame.style.setProperty('--float',`${mostlyFixed?4.6+(i%3)*.25:medium?3.7+(i%4)*.26:3+(i%6)*.27}s`);host.appendChild(frame)})}
 function display(){if(mode!=='alert'||showing||!queue.length||!stage)return;showing=true;const item=queue.shift(),style=['harmful','beneficial','neutral'].includes(item.alert_style)?item.alert_style:'neutral';stage.replaceChildren();stage.className=`bits-alert-stage style-${style}`;const scene=document.createElement('div');scene.className='bits-alert-scene';const src=imageUrl(item.image);addParticles(scene,item,style);if(src)scene.appendChild(diamond(src,'bits-alert-main'));const message=document.createElement('div');message.className='bits-alert-message';if(demo){const note=document.createElement('span');note.className='bits-demo-label';note.textContent='PRUEBA · NO AGREGA ENTRADAS';message.appendChild(note)}const headline=document.createElement('strong');headline.textContent=`${item.donor} DONÓ ${item.bits} BITS`;const copy=document.createElement('p');copy.textContent=`AGREGÓ ${item.quantity>1?item.quantity+' × ':''}${item.item_name} A LA RULETA`;message.append(headline,copy);scene.appendChild(message);stage.appendChild(scene);stage.hidden=false;playSound(style);setTimeout(()=>{stage.classList.add('is-leaving');setTimeout(()=>{stage.hidden=true;stage.className='bits-alert-stage';stage.replaceChildren();showing=false;display()},650)},6500)}
 function liveItems(){return timersPaused?active.filter(item=>!item.expires_at||item.paused_remaining_seconds!==null):active.filter(item=>!item.expires_at||Date.parse(item.expires_at)>Date.now())}
 function renderDock(){if(mode!=='active'||!dock)return;const items=liveItems();if(!items.length){dock.hidden=true;dock.replaceChildren();return}dock.hidden=false;const pageSize=5;if(offset>=items.length)offset=0;const visible=items.length<=pageSize?items:Array.from({length:Math.min(pageSize,items.length)},(_,i)=>items[(offset+i)%items.length]);dock.replaceChildren();const head=document.createElement('div');head.className='bits-dock-head';head.innerHTML=`<span>${timersPaused?'ENTRADAS ACTIVAS · PAUSADAS':'ENTRADAS ACTIVAS'}</span><b>${items.length}</b>`;const list=document.createElement('div');list.className='bits-dock-list';for(const item of visible){const row=document.createElement('article');row.className='bits-dock-item';row.innerHTML=`<div><strong>${item.donor}</strong><p>agregó ${item.quantity} × ${item.item_name}</p></div><span class="bits-dock-time${timersPaused&&item.expires_at?' is-paused':''}">${remaining(item)}</span>`;list.appendChild(row)}dock.append(head,list);dock.classList.toggle('is-rotating',items.length>pageSize)}
 function scheduleRotation(){clearInterval(rotateTimer);rotateTimer=setInterval(()=>{if(mode!=='active')return;const items=liveItems();if(items.length>5){offset=(offset+1)%items.length;dock?.classList.remove('dock-shift');void dock?.offsetWidth;dock?.classList.add('dock-shift');renderDock()}},6500)}
 let pollFailures=0;
 async function poll(){try{const endpoint=window.SANLEAN_SUPABASE.url+'/functions/v1/stream-bits/alerts?token='+encodeURIComponent(token)+(cursor!==null?'&after='+encodeURIComponent(cursor):'');const r=await fetch(endpoint,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('Alert request failed');{const data=await r.json();pollFailures=0;cursor=data.cursor;sound=data.sound;active=data.active||[];timersPaused=!!data.timersPaused;if(mode==='alert'){const events=(data.events||[]).filter(item=>!alertFilter||item.alert_style===alertFilter);queue.push(...events)}renderDock();display()}}catch{pollFailures=Math.min(pollFailures+1,6)}finally{const base=mode==='active'?5000:2000;setTimeout(poll,pollFailures?Math.min(30000,base*2**pollFailures):base)}}
 setInterval(renderDock,1000);scheduleRotation();
 if(mode==='alert'){Promise.all(['harmful','beneficial'].map(style=>defaultAudioUrl(style).catch(()=>'')));resolveCustomSounds(true)}
 if(demo){const now=Date.now();if(mode==='active'){active=[{donor:'PEDRITO33',bits:300,quantity:1,item_name:'ME LA PELA',expires_at:new Date(now+60*60*1000).toISOString(),paused_remaining_seconds:null,alert_style:'harmful'},{donor:'LUNA_DBD',bits:600,quantity:1,item_name:'AGILIDAD',expires_at:new Date(now+38*60*60*1000).toISOString(),paused_remaining_seconds:null,alert_style:'beneficial'},{donor:'NICO',bits:200,quantity:1,item_name:'AGITACIÓN',expires_at:null,paused_remaining_seconds:null,alert_style:'neutral'}];renderDock()}else{const harmful=demoStyle==='harmful',beneficial=demoStyle==='beneficial';queue.push({donor:harmful?'PEDRITO33':beneficial?'LUNA_DBD':'DONADOR DE PRUEBA',bits:harmful?500:beneficial?600:300,quantity:1,item_name:harmful?'ME LA PELA':beneficial?'AGILIDAD':'AGITACIÓN',image:harmful?'../survivor/30_noMither.png':beneficial?'../survivor/29_lithe.png':'../killer/01_agitation.png',alert_style:demoStyle});setTimeout(display,250)}}else if(token)poll();
})();