(()=>{
 const params=new URLSearchParams(location.search),token=params.get('token'),demo=params.get('demo')==='1',root=document.getElementById('bitsAlert'),dock=document.getElementById('bitsActiveDock'),queue=[],audio=new Audio('../assets/usuario/bits-surprise.wav');audio.preload='auto';audio.volume=.45;
 let showing=false,cursor=null,sound=true,active=[],offset=0,rotateTimer=null;
 const imageUrl=value=>{try{const u=new URL(value,location.href);return u.origin===location.origin&&/\.png$/.test(u.pathname)?u.href:''}catch{return''}};
 const remaining=expires=>{if(!expires)return'HASTA ELIMINAR';const ms=Date.parse(expires)-Date.now();if(ms<=0)return'FINALIZADA';const total=Math.ceil(ms/1000),h=Math.floor(total/3600),m=Math.floor((total%3600)/60),s=total%60;if(h)return`${h}H ${String(m).padStart(2,'0')}M`;if(m)return`${m}M ${String(s).padStart(2,'0')}S`;return`${s}S`};
 function display(){if(showing||!queue.length)return;showing=true;const item=queue.shift();root.replaceChildren();if(demo){const note=document.createElement('p');note.className='bits-demo-label';note.textContent='PRUEBA · NO AGREGA ENTRADAS';root.appendChild(note)}const img=document.createElement('img');img.src=imageUrl(item.image);img.alt='';const donor=document.createElement('strong');donor.textContent=item.donor;const title=document.createElement('h1');title.textContent=item.bits+' BITS';const text=document.createElement('p');text.textContent=`${item.donor} agregó ${item.quantity} × ${item.item_name} a la ruleta`;root.append(img,donor,title,text);root.hidden=false;if(sound){audio.currentTime=0;audio.play().catch(()=>{})}setTimeout(()=>{root.hidden=true;showing=false;display()},6500)}
 function liveItems(){return active.filter(item=>!item.expires_at||Date.parse(item.expires_at)>Date.now())}
 function renderDock(){const items=liveItems();if(!dock)return;if(!items.length){dock.hidden=true;dock.replaceChildren();return}dock.hidden=false;const pageSize=5;if(offset>=items.length)offset=0;const visible=items.length<=pageSize?items:Array.from({length:Math.min(pageSize,items.length)},(_,i)=>items[(offset+i)%items.length]);dock.replaceChildren();const head=document.createElement('div');head.className='bits-dock-head';head.innerHTML=`<span>ENTRADAS ACTIVAS</span><b>${items.length}</b>`;const list=document.createElement('div');list.className='bits-dock-list';for(const item of visible){const row=document.createElement('article');row.className='bits-dock-item';row.innerHTML=`<div><strong>${item.donor}</strong><p>agregó ${item.quantity} × ${item.item_name}</p></div><span class="bits-dock-time">${remaining(item.expires_at)}</span>`;list.appendChild(row)}dock.append(head,list);if(items.length>pageSize)dock.classList.add('is-rotating');else dock.classList.remove('is-rotating')}
 function scheduleRotation(){clearInterval(rotateTimer);rotateTimer=setInterval(()=>{const items=liveItems();if(items.length>5){offset=(offset+1)%items.length;dock?.classList.remove('dock-shift');void dock?.offsetWidth;dock?.classList.add('dock-shift');renderDock()}},6500)}
 async function poll(){try{const endpoint=window.SANLEAN_SUPABASE.url+'/functions/v1/stream-bits/alerts?token='+encodeURIComponent(token)+(cursor!==null?'&after='+encodeURIComponent(cursor):'');const r=await fetch(endpoint,{cache:'no-store',signal:AbortSignal.timeout(12000)});if(r.ok){const data=await r.json();cursor=data.cursor;sound=data.sound;active=data.active||[];queue.push(...(data.events||[]));renderDock();display()}}catch{}finally{setTimeout(poll,1500)}}
 setInterval(renderDock,1000);scheduleRotation();
 if(demo){const button=document.getElementById('bitsDemo');button.hidden=false;const now=Date.now();active=[{donor:'PEDRITO33',bits:300,quantity:1,item_name:'AGITACIÓN',expires_at:new Date(now+60*60*1000).toISOString()},{donor:'LUNA_DBD',bits:500,quantity:2,item_name:'ME LA PELA',expires_at:new Date(now+38*60*1000).toISOString()},{donor:'NICO',bits:200,quantity:1,item_name:'OBJETO DE OBSESIÓN',expires_at:null}];renderDock();button.onclick=()=>{queue.push({donor:'DONADOR DE PRUEBA',bits:300,quantity:1,item_name:'AGITACIÓN',image:'../assets/killers/K09_TheCannibal_Portrait.png'});display()}}else if(token)poll();
})();
