(()=>{if(!document.querySelector('link[data-unified-section-titles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='css/unified-section-titles.css?v=1';l.dataset.unifiedSectionTitles='1';document.head.appendChild(l)}})();
document.addEventListener('DOMContentLoaded', function () {
  document.querySelectorAll('.has-dropdown').forEach(item=>{const label=item.querySelector(':scope > .nav-link');if(!label||label.textContent.trim().toUpperCase()!=='DEAD BY DAYLIGHT')return;const menu=item.querySelector(':scope > .dropdown');if(menu&&![...menu.querySelectorAll('a')].some(a=>a.textContent.trim().toUpperCase()==='1VS1')){const li=document.createElement('li'),a=document.createElement('a');a.href='1vs1.html';a.textContent='1VS1';li.appendChild(a);menu.appendChild(li)}});
  if(document.querySelector('.perk-search')&&!document.querySelector('script[data-search-aliases]')){const s=document.createElement('script');s.src='js/search-aliases.js?v=2';s.dataset.searchAliases='1';document.head.appendChild(s)}
  const splash=document.getElementById('splash');if(splash){const skip=new URLSearchParams(location.search).get('skipSplash')==='1';if(skip){splash.remove();document.body.classList.remove('no-scroll');history.replaceState&&history.replaceState({},'','index.html')}else{let dismissed=false;document.body.classList.add('no-scroll');const hide=()=>{if(dismissed)return;dismissed=true;splash.classList.add('splash-hidden');document.body.classList.remove('no-scroll');setTimeout(()=>splash.remove(),700)};splash.addEventListener('click',hide);setTimeout(hide,4200)}}
  const menuToggle=document.getElementById('menuToggle'),mainNav=document.getElementById('mainNav');if(menuToggle&&mainNav)menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('nav-open');menuToggle.classList.toggle('is-open',open);menuToggle.setAttribute('aria-expanded',String(open))});
  document.querySelectorAll('.has-dropdown > .nav-link').forEach(link=>link.addEventListener('click',e=>{if(matchMedia('(max-width:900px)').matches){e.preventDefault();e.stopPropagation();link.parentElement.classList.toggle('dropdown-open');return}if(link.textContent.trim().toUpperCase()==='DEAD BY DAYLIGHT')location.href='index.html?skipSplash=1'}));
  if(document.querySelectorAll('.config-section').length){const b=document.createElement('button');b.type='button';b.className='back-to-top';b.setAttribute('aria-label','Volver arriba');b.innerHTML='&#8593;';document.body.appendChild(b);const update=()=>b.classList.toggle('visible',!!document.querySelector('.config-grid.open')&&scrollY>360);addEventListener('scroll',update,{passive:true});document.addEventListener('click',()=>setTimeout(update,0));b.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));update()}
  const reel=document.getElementById('killerReel'),spinBtn=document.getElementById('spinKillerBtn');if(!reel||!spinBtn)return;
  const oldCanvas=document.getElementById('killerTrack');if(oldCanvas)oldCanvas.classList.add('legacy-killer-canvas');const track=document.createElement('div');track.className='killer-track';track.id='killerDomTrack';reel.insertBefore(track,reel.querySelector('.reel-edge-left'));
  let killers=[],order=[],spinning=false,lastWinnerKey=null;const step=()=>matchMedia('(max-width:700px)').matches?164:210;function shuffle(a){a=a.slice();for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function card(k){const c=document.createElement('div');c.className='killer-card';if(!k){c.classList.add('killer-card-spacer');c.style.visibility='hidden';return c}c.dataset.key=k.key;const frame=document.createElement('img');frame.className='killer-card-frame';frame.src='rectangulo-fondo.png';frame.alt='';const img=document.createElement('img');img.className='killer-card-portrait';img.src=k.image;img.alt=k.name;img.draggable=false;const name=document.createElement('div');name.className='killer-card-name';name.textContent=k.name==='Jason (El Destripador)'?'Jason':k.name;c.append(frame,img,name);return c}
  function render(a){track.replaceChildren(...a.map(card));order=a.slice()}function center(i){const s=step(),x=-(i*s+(s-14)/2);track.getAnimations().forEach(a=>a.cancel());track.style.transform=`translate3d(${x}px,-50%,0)`}
  function enabled(){const disabled=new Set();document.querySelectorAll('#cfgKillersGrid .config-item.disabled .cfg-name').forEach(e=>disabled.add(e.textContent.trim().toLowerCase()));return killers.filter(k=>!disabled.has(k.name.trim().toLowerCase()))}
  function buildSpinStrip(pool,winner){const shuffled=shuffle(pool),winnerPos=shuffled.findIndex(k=>k.key===winner.key);const unique=shuffled.slice(winnerPos+1).concat(shuffled.slice(0,winnerPos),winner);const padding=3,travel=52,strip=new Array(padding).fill(null);for(let i=0;i<travel;i++)strip.push(unique[i%unique.length]);const finalOrder=shuffle(pool.filter(k=>k.key!==winner.key));const leftCount=Math.min(3,Math.floor((pool.length-1)/2)),rightCount=Math.min(3,pool.length-1-leftCount);const left=finalOrder.slice(0,leftCount),right=finalOrder.slice(leftCount,leftCount+rightCount);const wi=strip.length+left.length;strip.push(...left,winner,...right);while(strip.length<wi+4)strip.push(null);return{strip,wi,startIndex:padding}}
  async function spin(){if(spinning||killers.length<2)return;const pool=enabled();if(pool.length<2)return;spinning=true;spinBtn.disabled=true;track.querySelectorAll('.selected').forEach(c=>c.classList.remove('selected'));let choices=pool.filter(k=>k.key!==lastWinnerKey);if(!choices.length)choices=pool;const winner=choices[Math.floor(Math.random()*choices.length)],{strip,wi,startIndex}=buildSpinStrip(pool,winner);render(strip);const s=step(),sx=-(startIndex*s+(s-14)/2),ex=-(wi*s+(s-14)/2);track.style.transform=`translate3d(${sx}px,-50%,0)`;track.getBoundingClientRect();const anim=track.animate([{transform:`translate3d(${sx}px,-50%,0)`,offset:0},{transform:`translate3d(${sx+(ex-sx)*.72}px,-50%,0)`,offset:.60},{transform:`translate3d(${sx+(ex-sx)*.92}px,-50%,0)`,offset:.84},{transform:`translate3d(${ex}px,-50%,0)`,offset:1}],{duration:8000,easing:'cubic-bezier(.12,.72,.16,1)',fill:'forwards'});try{await anim.finished}catch(e){}track.style.transform=`translate3d(${ex}px,-50%,0)`;anim.cancel();const selected=[...track.querySelectorAll('.killer-card')][wi];if(selected)selected.classList.add('selected');lastWinnerKey=winner.key;spinning=false;spinBtn.disabled=false}
  spinBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();spin()},true);fetch('data/killers.json',{cache:'no-store'}).then(r=>r.json()).then(data=>{killers=data.filter(k=>k&&k.key&&k.image);order=shuffle(killers);render(order);center(Math.min(Math.floor(order.length/2),order.length-1))}).catch(console.error);addEventListener('resize',()=>{if(spinning||!order.length)return;const sel=track.querySelector('.selected'),i=sel?[...track.children].indexOf(sel):Math.floor(order.length/2);center(Math.max(0,i))});
  const config=document.getElementById('killerConfigSection'),toggle=document.getElementById('cfgKillersToggle');if(config&&toggle){config.classList.add('gear-controlled');const controls=document.createElement('div');controls.className='killer-spin-controls';spinBtn.parentNode.insertBefore(controls,spinBtn);controls.appendChild(spinBtn);const gear=document.createElement('button');gear.type='button';gear.className='killer-gear-btn';gear.setAttribute('aria-label','Configurar Killers');gear.setAttribute('data-tooltip','Configurar Killers');gear.innerHTML='&#9881;';controls.appendChild(gear);gear.addEventListener('click',()=>{const opening=!config.classList.contains('gear-visible');config.classList.toggle('gear-visible',opening);gear.classList.toggle('active',opening);gear.setAttribute('aria-expanded',String(opening));const grid=document.getElementById('cfgKillersGrid');if(grid)grid.classList.toggle('open',opening);config.classList.toggle('open',opening);if(opening)setTimeout(()=>config.scrollIntoView({behavior:'smooth',block:'start'}),80)})}
});