(()=>{if(!document.querySelector('link[data-unified-section-titles]')){const l=document.createElement('link');l.rel='stylesheet';l.href='css/unified-section-titles.css?v=1';l.dataset.unifiedSectionTitles='1';document.head.appendChild(l)}})();
document.addEventListener('DOMContentLoaded',function(){
 document.querySelectorAll('.has-dropdown').forEach(item=>{const label=item.querySelector(':scope > .nav-link');if(!label||label.textContent.trim().toUpperCase()!=='DEAD BY DAYLIGHT')return;const menu=item.querySelector(':scope > .dropdown');if(menu&&![...menu.querySelectorAll('a')].some(a=>a.textContent.trim().toUpperCase()==='1VS1')){const li=document.createElement('li'),a=document.createElement('a');a.href='1vs1.html';a.textContent='1VS1';li.appendChild(a);menu.appendChild(li)}});
 if(document.querySelector('.perk-search')&&!document.querySelector('script[data-search-aliases]')){const s=document.createElement('script');s.src='js/search-aliases.js?v=2';s.dataset.searchAliases='1';document.head.appendChild(s)}
 const splash=document.getElementById('splash');if(splash){const skip=new URLSearchParams(location.search).get('skipSplash')==='1';if(skip){splash.remove();document.body.classList.remove('no-scroll');history.replaceState&&history.replaceState({},'','index.html')}else{let dismissed=false;document.body.classList.add('no-scroll');const hide=()=>{if(dismissed)return;dismissed=true;splash.classList.add('splash-hidden');document.body.classList.remove('no-scroll');setTimeout(()=>splash.remove(),700)};splash.addEventListener('click',hide);setTimeout(hide,4200)}}
 const menuToggle=document.getElementById('menuToggle'),mainNav=document.getElementById('mainNav');if(menuToggle&&mainNav)menuToggle.addEventListener('click',()=>{const open=mainNav.classList.toggle('nav-open');menuToggle.classList.toggle('is-open',open);menuToggle.setAttribute('aria-expanded',String(open))});
 document.querySelectorAll('.has-dropdown > .nav-link').forEach(link=>link.addEventListener('click',e=>{if(matchMedia('(max-width:900px)').matches){e.preventDefault();e.stopPropagation();link.parentElement.classList.toggle('dropdown-open');return}if(link.textContent.trim().toUpperCase()==='DEAD BY DAYLIGHT')location.href='index.html?skipSplash=1'}));
 if(document.querySelectorAll('.config-section').length){const b=document.createElement('button');b.type='button';b.className='back-to-top';b.setAttribute('aria-label','Volver arriba');b.innerHTML='&#8593;';document.body.appendChild(b);const update=()=>b.classList.toggle('visible',!!document.querySelector('.config-grid.open')&&scrollY>360);addEventListener('scroll',update,{passive:true});document.addEventListener('click',()=>setTimeout(update,0));b.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));update()}
 const reel=document.getElementById('killerReel'),spinBtn=document.getElementById('spinKillerBtn');if(!reel||!spinBtn)return;
 const STORAGE='sanlean-roulette-simulation-v1',oldCanvas=document.getElementById('killerTrack');if(oldCanvas)oldCanvas.classList.add('legacy-killer-canvas');let track=document.getElementById('killerDomTrack');if(!track){track=document.createElement('div');track.className='killer-track';track.id='killerDomTrack';reel.insertBefore(track,reel.querySelector('.reel-edge-left'))}
 let killers=[],state={},entries=[],spinning=false,lastDeck=[];const step=()=>matchMedia('(max-width:700px)').matches?164:210;
 function esc(s){return String(s)}function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
 function readPanel(){try{state=JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch(e){state={}}state.weights=state.weights||{};state.bonusEntries=state.bonusEntries||{};return Object.keys(state.weights).some(k=>k.startsWith('killers:'))||Object.keys(state.bonusEntries).some(k=>k.startsWith('killers:'))}
 function panelWeight(k){const v=state.weights['killers:'+k.key];return v===undefined?1:Math.max(0,Number(v)||0)}function panelDonors(k){const a=state.bonusEntries['killers:'+k.key];return Array.isArray(a)?a.map(v=>String(v||'').trim()).filter(Boolean):[]}
 function localDisabled(){const set=new Set();document.querySelectorAll('#cfgKillersGrid .config-item.disabled').forEach(el=>{const key=el.dataset&&el.dataset.key;if(key)set.add(key);const n=el.querySelector('.cfg-name');if(n)set.add(n.textContent.trim().toLowerCase())});return set}
 function rebuild(){const panel=readPanel(),disabled=localDisabled();entries=[];for(const k of killers){if(!k||!k.key||!k.image)continue;if(panel){const w=panelWeight(k);if(w<=0)continue;entries.push({killer:k,donor:null,id:k.key+':base'});const ds=panelDonors(k);ds.forEach((d,i)=>entries.push({killer:k,donor:d,id:k.key+':donor:'+i}));for(let i=0;i<Math.max(0,w-1-ds.length);i++)entries.push({killer:k,donor:null,id:k.key+':extra:'+i})}else{if(disabled.has(k.key)||disabled.has(k.name.trim().toLowerCase()))continue;entries.push({killer:k,donor:null,id:k.key+':base'})}}return panel}
 function card(e){const c=document.createElement('div');c.className='killer-card'+(e.donor?' donated':'');c.dataset.key=e.killer.key;c.dataset.entryId=e.id;const frame=document.createElement('img');frame.className='killer-card-frame';frame.src='rectangulo-fondo.png';frame.alt='';const img=document.createElement('img');img.className='killer-card-portrait';img.src=e.killer.image;img.alt=e.killer.name;img.draggable=false;const name=document.createElement('div');name.className='killer-card-name';name.textContent=e.killer.name==='Jason (El Destripador)'?'Jason':e.killer.name;c.append(frame,img,name);if(e.donor){const d=document.createElement('div');d.className='killer-card-donor';d.textContent=e.donor;c.appendChild(d)}return c}
 function noAdjacent(source,previous=null){const pool=[...source],out=[];let prev=previous;while(pool.length){const choices=[];for(let i=0;i<pool.length;i++)if(pool[i].killer.key!==prev)choices.push(i);const pick=choices.length?choices[Math.floor(Math.random()*choices.length)]:Math.floor(Math.random()*pool.length),e=pool.splice(pick,1)[0];out.push(e);prev=e.killer.key}return out}
 function longDeck(min){const out=[];let prev=null;while(out.length<min){const batch=noAdjacent(entries,prev);out.push(...batch);prev=out.length?out[out.length-1].killer.key:null}return out.slice(0,Math.max(min,entries.length*8))}
 function render(deck){track.replaceChildren(...deck.map(card));lastDeck=deck}function offset(i){const s=step();return -(i*s+(s-14)/2)}function center(i){track.getAnimations().forEach(a=>a.cancel());track.style.transition='none';track.style.transform=`translate3d(${offset(i)}px,-50%,0)`}
 function idle(){rebuild();if(!entries.length){track.replaceChildren();spinBtn.disabled=true;return}const deck=longDeck(Math.max(18,entries.length*3));render(deck);center(Math.min(6,deck.length-1));spinBtn.disabled=entries.length<2}
 async function spin(){if(spinning)return;rebuild();if(entries.length<2)return;spinning=true;spinBtn.disabled=true;const deck=longDeck(Math.max(100,entries.length*10)),start=5,target=deck.length-7;render(deck);const sx=offset(start),ex=offset(target);track.style.transition='none';track.style.transform=`translate3d(${sx}px,-50%,0)`;track.getBoundingClientRect();const anim=track.animate([{transform:`translate3d(${sx}px,-50%,0)`,offset:0},{transform:`translate3d(${sx+(ex-sx)*.72}px,-50%,0)`,offset:.60},{transform:`translate3d(${sx+(ex-sx)*.92}px,-50%,0)`,offset:.84},{transform:`translate3d(${ex}px,-50%,0)`,offset:1}],{duration:8000,easing:'cubic-bezier(.12,.72,.16,1)',fill:'forwards'});try{await anim.finished}catch(e){}track.style.transform=`translate3d(${ex}px,-50%,0)`;anim.cancel();const winner=track.children[target];if(winner)winner.classList.add('selected');spinning=false;spinBtn.disabled=false}
 spinBtn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();spin()},true);
 fetch('data/killers.json',{cache:'no-store'}).then(r=>r.json()).then(data=>{killers=data.filter(k=>k&&k.key&&k.image);idle()}).catch(console.error);
 addEventListener('resize',()=>{if(spinning||!lastDeck.length)return;const sel=track.querySelector('.selected'),i=sel?[...track.children].indexOf(sel):Math.min(6,lastDeck.length-1);center(Math.max(0,i))});
 addEventListener('focus',()=>{if(!spinning)idle()});addEventListener('storage',e=>{if(e.key===STORAGE&&!spinning)idle()});
 const panelActive=readPanel(),gear=document.getElementById('killerGearBtn'),config=document.getElementById('killerConfigSection');if(panelActive&&gear){gear.hidden=true;if(config){config.classList.remove('gear-visible','open');config.style.display='none'}}
});