/* Presentation shared only by USUARIO and its OBS sources. Killer motion mirrors WEB ruleta-killer. */
(()=>{
  const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const imageUrl=value=>{try{const url=new URL(value,location.href);return url.origin===location.origin&&/\.png$/i.test(url.pathname)?url.href:''}catch{return''}};
  const imageCache=new Map();
  function loadImage(src){if(!src)return Promise.resolve(null);if(imageCache.has(src))return imageCache.get(src);const promise=new Promise(resolve=>{const img=new Image();img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=src});imageCache.set(src,promise);return promise}
  function easeOutQuint(t){return 1-Math.pow(1-t,5)}
  function drawPerk(ctx,img,x,y,w,h){if(!img)return;const pad=w*.08,boxW=w-pad*2,boxH=h-pad*2,ratio=img.width/img.height;let dw=boxW,dh=boxW/ratio;if(dh>boxH){dh=boxH;dw=boxH*ratio}ctx.drawImage(img,x+pad+(boxW-dw)/2,y+pad+(boxH-dh)/2,dw,dh)}
  function itemMarkup(item){const src=imageUrl(item?.image),empty=!item||item.emptySlot||item.key==='slot_vacio',name=item?.name||'',longName=name.length>14;return `<div class="sl-roulette-frame is-perk${empty?' is-empty':''}">${!empty&&src?`<img src="${escape(src)}" alt="" decoding="async">`:''}</div>${name?`<strong class="sl-roulette-name${longName?' is-long-name':''}">${escape(name)}</strong>`:''}${item?.donor?`<span class="sl-roulette-donor">${escape(item.donor)}</span>`:''}`}
  async function animatePerkCanvas(canvas,pool,target,delay=0){if(!canvas||!target||canvas.dataset.spinning==='true')return;canvas.dataset.spinning='true';const usable=(pool||[]).filter(x=>x&&!x.emptySlot&&x.key!=='slot_vacio'&&imageUrl(x.image)),sequence=[];for(let i=0;i<36;i++)sequence.push(usable[Math.floor(Math.random()*usable.length)]||target);sequence.push(target);await Promise.all(sequence.filter(x=>!x.emptySlot).map(x=>loadImage(imageUrl(x.image))));if(delay)await new Promise(r=>setTimeout(r,delay));if(!canvas.isConnected)return;const ctx=canvas.getContext('2d');if(!ctx)return;const cssWidth=canvas.clientWidth||180,cssHeight=canvas.clientHeight||180,dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(cssWidth*dpr);canvas.height=Math.round(cssHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const end=sequence.length-1,startTime=performance.now(),duration=3000;function frame(now){if(!canvas.isConnected)return;const progress=Math.min(1,(now-startTime)/duration),position=end*easeOutQuint(progress);ctx.clearRect(0,0,cssWidth,cssHeight);const first=Math.floor(position)-2;for(let i=first;i<=first+6;i++){if(i<0||i>=sequence.length)continue;const item=sequence[i];if(item.emptySlot)continue;const cached=imageCache.get(imageUrl(item.image));if(cached instanceof Promise)cached.then(img=>{if(canvas.dataset.spinning==='true'&&canvas.isConnected)drawPerk(ctx,img,0,(i-position)*cssHeight,cssWidth,cssHeight)})}if(progress>=1){ctx.clearRect(0,0,cssWidth,cssHeight);const final=imageCache.get(imageUrl(target.image));if(final instanceof Promise)final.then(img=>{if(canvas.isConnected){ctx.clearRect(0,0,cssWidth,cssHeight);drawPerk(ctx,img,0,0,cssWidth,cssHeight)}});canvas.dataset.spinning='false';return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

  const killerFrame=loadImage(`${location.origin}/Rectangulo.png`);
  function killerEntries(pool){const out=[];(pool||[]).forEach(k=>{if(!k?.image||Number(k.weight)<=0)return;const donors=Array.isArray(k.donors)?k.donors.filter(Boolean):[];out.push({item:k,donor:null});donors.forEach(d=>out.push({item:k,donor:d}));for(let i=0;i<Math.max(0,Math.floor(Number(k.weight)||1)-1-donors.length);i++)out.push({item:k,donor:null})});return out}
  function spreadEntries(source,previousKey=null){const pool=[...source],out=[];let prev=previousKey;while(pool.length){const counts={};pool.forEach(e=>counts[e.item.key]=(counts[e.item.key]||0)+1);let candidates=pool.map((e,i)=>({e,i,count:counts[e.item.key]})).filter(x=>x.e.item.key!==prev);if(!candidates.length)candidates=pool.map((e,i)=>({e,i,count:counts[e.item.key]}));const max=Math.max(...candidates.map(x=>x.count)),preferred=candidates.filter(x=>x.count===max),pick=preferred[Math.floor(Math.random()*preferred.length)],chosen=pool.splice(pick.i,1)[0];out.push(chosen);prev=chosen.item.key}return out}
  function setupKillerCanvas(canvas){const w=canvas.clientWidth||1180,h=canvas.clientHeight||370,dpr=Math.min(window.devicePixelRatio||1,2),ctx=canvas.getContext('2d');if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);return{ctx,w,h}}
  function wrapName(name){const n=String(name||'').toUpperCase();if(n.length>20&&n.includes(' ')){const words=n.split(' ');let a='',b='';for(const word of words){if((a+' '+word).trim().length<=Math.ceil(n.length/2)+2)a=(a+' '+word).trim();else b=(b+' '+word).trim()}return b?[a,b]:[n]}return[n]}
  function fitPortrait(ctx,img,x,y,w,h){if(!img||!img.complete||!img.naturalWidth)return;const s=Math.min(w/img.naturalWidth,h/img.naturalHeight)*1.19,iw=img.naturalWidth*s,ih=img.naturalHeight*s;ctx.drawImage(img,x+(w-iw)/2,y+(h-ih)/2,iw,ih)}
  function drawKillerCard(ctx,entry,x,itemW,h,selected=false,alpha=1){if(!entry?.item)return;const k=entry.item,src=imageUrl(k.image),promise=imageCache.get(src);ctx.save();ctx.globalAlpha=alpha;const scale=selected?1.22:1,cardW=(itemW-14)*scale,cardH=(h-92)*scale,cx=x+itemW/2,cy=h/2,cardX=cx-cardW/2,cardY=cy-cardH/2;if(selected&&entry.donor){ctx.shadowColor='#ff003c';ctx.shadowBlur=30}ctx.fillStyle='rgba(3,3,4,.94)';ctx.fillRect(cardX,cardY,cardW,cardH);ctx.shadowBlur=0;killerFrame.then(frame=>{if(frame&&ctx.canvas.isConnected){ctx.save();ctx.globalAlpha=.72;ctx.drawImage(frame,cardX,cardY,cardW,cardH);ctx.restore()}});if(promise instanceof Promise)promise.then(img=>{if(!img||!ctx.canvas.isConnected)return;ctx.save();ctx.beginPath();ctx.rect(cardX+8,cardY+7,cardW-16,cardH-50);ctx.clip();ctx.filter='brightness(1.23) contrast(1.035)';fitPortrait(ctx,img,cardX+8,cardY+7,cardW-16,cardH-50);ctx.filter='none';ctx.restore()});ctx.fillStyle='#fff';ctx.shadowColor='rgba(0,0,0,.9)';ctx.shadowBlur=4;const lines=wrapName(k.name),fontSize=selected?19:17;ctx.font=`800 ${fontSize}px Montserrat,Arial,sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';const baseY=cardY+cardH-(lines.length===2?43:31);lines.forEach((line,i)=>ctx.fillText(line,cx,baseY+i*(fontSize+2),cardW-18));if(entry.donor){ctx.shadowColor='rgba(0,0,0,.95)';ctx.shadowBlur=8;ctx.fillStyle='#ff003c';ctx.font=`800 ${fontSize}px Montserrat,Arial,sans-serif`;ctx.fillText(entry.donor,cx,cy,cardW-22)}ctx.restore()}
  function renderKillerAt(canvas,seq,pos,selectedIndex=-1){const{ctx,w,h}=setupKillerCanvas(canvas),itemW=210,center=w/2;ctx.clearRect(0,0,w,h);const first=Math.max(0,Math.floor(pos)-5),last=Math.min(seq.length-1,Math.ceil(pos)+5);for(let i=first;i<=last;i++){const x=center+(pos-i)*itemW-itemW/2;if(x<-itemW*1.3||x>w+itemW*.3)continue;const dist=Math.abs(x+itemW/2-center);drawKillerCard(ctx,seq[i],x,itemW,h,i===selectedIndex,Math.max(.74,1-dist/(w*1.7)))}}
  async function preloadKillerEntries(entries){await Promise.all(entries.map(e=>loadImage(imageUrl(e.item.image))));await killerFrame}
  function staticKiller(canvas,pool,winner=null){const entries=killerEntries(pool);if(!entries.length)return;let row=spreadEntries(entries);while(row.length<7)row.push(...spreadEntries(entries,row.length?row[row.length-1].item.key:null));row=row.slice(0,7);let selected=-1;if(winner){row[3]={item:winner,donor:winner.donor||null};selected=3}preloadKillerEntries(row).then(()=>renderKillerAt(canvas,row,3,selected))}
  async function spinKiller(canvas,pool,winner,duration=8000){const entries=killerEntries(pool);if(!entries.length||!winner){staticKiller(canvas,pool,winner);return}await preloadKillerEntries(entries);const cycles=Math.max(6,Math.ceil(90/entries.length)),deck=[];let previousKey=null;for(let c=0;c<cycles;c++){const batch=spreadEntries(entries,previousKey);deck.push(...batch);previousKey=deck[deck.length-1].item.key}const targetIndex=Math.max(0,deck.length-7);deck[targetIndex]={item:winner,donor:winner.donor||null};const start=performance.now(),brakeStart=.78;function frame(now){if(!canvas.isConnected)return;const p=Math.min(1,(now-start)/duration);let progress;if(p<brakeStart)progress=(p/brakeStart)*.86;else{const q=(p-brakeStart)/(1-brakeStart);progress=.86+.14*(1-Math.pow(1-q,4))}renderKillerAt(canvas,deck,targetIndex*progress,-1);if(p<1)return requestAnimationFrame(frame);const from=Math.max(0,targetIndex-3),row=deck.slice(from,Math.min(deck.length,targetIndex+4)),selected=targetIndex-from;renderKillerAt(canvas,row,selected,selected)}requestAnimationFrame(frame)}
  function paintKiller(target,data){const state=data?.state||{},pool=state.spinPool||data?.settings?.pool||[],winner=(state.targets||[])[0]||(state.items||[])[0]||null;target.innerHTML='<div class="sl-killer-web"><h2>RULETA DE <span>KILLERS</span> DE DBD</h2><div class="sl-killer-web-reel"><canvas class="sl-killer-web-canvas"></canvas><div class="sl-killer-edge sl-killer-edge-left"></div><div class="sl-killer-edge sl-killer-edge-right"></div><div class="sl-killer-marker sl-killer-marker-top"></div><div class="sl-killer-marker sl-killer-marker-bottom"></div></div></div>';const canvas=target.querySelector('.sl-killer-web-canvas');if(state.status==='spinning')spinKiller(canvas,pool,winner,Number(state.durationMs)||8000);else staticKiller(canvas,pool,state.status==='result'?winner:null)}
  function paintPerks(target,data){const state=data?.state||{},pool=data?.settings?.pool||[],spinning=state.status==='spinning',result=state.status==='result',items=state.items||[],targets=state.targets||[],chaotic=state.cardRule?.event==='chaotic',slots=4,active=spinning?(state.activeSlots||[0,1,2,3]):[];target.innerHTML=`<div class="sl-roulette${spinning?' is-spinning':''}${result?' is-result':''}${chaotic?' is-chaotic':''}"><div class="sl-roulette-slots">${Array.from({length:slots},(_,i)=>{if(spinning){const fixed=items[i]||null;if(active.includes(i))return `<article class="sl-roulette-slot is-rolling"><div class="sl-roulette-roll-shell"><canvas class="sl-roulette-canvas" data-slot="${i}"></canvas></div><div class="sl-roulette-label-space"></div></article>`;return `<article class="sl-roulette-slot${fixed?' is-result-slot':''}${!fixed?' is-inactive':''}">${itemMarkup(fixed)}</article>`}const item=items[i]||null;return `<article class="sl-roulette-slot${result&&item?' is-result-slot':''}${item?.donor?' has-donor':''}${!item?' is-inactive':''}">${itemMarkup(item)}</article>`}).join('')}</div></div>`;if(spinning)target.querySelectorAll('.sl-roulette-canvas').forEach(canvas=>{const i=Number(canvas.dataset.slot),targetItem=targets[i];if(targetItem)animatePerkCanvas(canvas,pool,targetItem,i*140)})}
  function render(target,data,{preview=false}={}){const state=data?.state||{},killer=data?.kind==='roulette_killers',items=state.items||[],targets=state.targets||[],pool=state.spinPool||data?.settings?.pool||[],signature=JSON.stringify([data.kind,state.status,state.visible,state.spinId,items.map(x=>x?.key),targets.map(x=>x?.key),state.activeSlots,state.cardRule?.resultId,state.cardRule?.event,pool.map(x=>x.key)]);if(target.dataset.rouletteSignature===signature)return;if(!preview&&state.visible===false){target.dataset.rouletteSignature=signature;target.innerHTML='';return}target.dataset.rouletteSignature=signature;killer?paintKiller(target,data):paintPerks(target,data)}
  window.SanLeanRouletteView={render};
})();