/* Presentation shared only by USUARIO and its OBS sources. Killer reel mirrors the operative WEB implementation. */
(()=>{
  const escape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const imageUrl=value=>{try{const url=new URL(value,location.href);return url.origin===location.origin&&/\.png$/i.test(url.pathname)?url.href:''}catch{return''}};
  const imageCache=new Map();
  function loadImage(src){if(!src)return Promise.resolve(null);if(imageCache.has(src))return imageCache.get(src);const promise=new Promise(resolve=>{const img=new Image();img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=src});imageCache.set(src,promise);return promise}
  function easeOutQuint(t){return 1-Math.pow(1-t,5)}
  function drawPerk(ctx,img,x,y,w,h){if(!img)return;const pad=w*.08,boxW=w-pad*2,boxH=h-pad*2,ratio=img.width/img.height;let dw=boxW,dh=boxW/ratio;if(dh>boxH){dh=boxH;dw=boxH*ratio}ctx.drawImage(img,x+pad+(boxW-dw)/2,y+pad+(boxH-dh)/2,dw,dh)}
  function itemMarkup(item){const src=imageUrl(item?.image),empty=!item||item.emptySlot||item.key==='slot_vacio',name=item?.name||'',longName=name.length>14;return `<div class="sl-roulette-frame is-perk${empty?' is-empty':''}">${!empty&&src?`<img src="${escape(src)}" alt="" decoding="async">`:''}</div>${name?`<strong class="sl-roulette-name${longName?' is-long-name':''}">${escape(name)}</strong>`:''}${item?.donor?`<span class="sl-roulette-donor">${escape(item.donor)}</span>`:''}`}
  async function animatePerkCanvas(canvas,pool,target,delay=0){if(!canvas||!target||canvas.dataset.spinning==='true')return;canvas.dataset.spinning='true';const usable=(pool||[]).filter(x=>x&&!x.emptySlot&&x.key!=='slot_vacio'&&imageUrl(x.image)),sequence=[];for(let i=0;i<36;i++)sequence.push(usable[Math.floor(Math.random()*usable.length)]||target);sequence.push(target);await Promise.all(sequence.filter(x=>!x.emptySlot).map(x=>loadImage(imageUrl(x.image))));if(delay)await new Promise(r=>setTimeout(r,delay));if(!canvas.isConnected)return;const ctx=canvas.getContext('2d');if(!ctx)return;const cssWidth=canvas.clientWidth||180,cssHeight=canvas.clientHeight||180,dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(cssWidth*dpr);canvas.height=Math.round(cssHeight*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const end=sequence.length-1,startTime=performance.now(),duration=3000;function frame(now){if(!canvas.isConnected)return;const progress=Math.min(1,(now-startTime)/duration),position=end*easeOutQuint(progress);ctx.clearRect(0,0,cssWidth,cssHeight);const first=Math.floor(position)-2;for(let i=first;i<=first+6;i++){if(i<0||i>=sequence.length)continue;const item=sequence[i];if(item.emptySlot)continue;const cached=imageCache.get(imageUrl(item.image));if(cached instanceof Promise)cached.then(img=>{if(canvas.dataset.spinning==='true'&&canvas.isConnected)drawPerk(ctx,img,0,(i-position)*cssHeight,cssWidth,cssHeight)})}if(progress>=1){ctx.clearRect(0,0,cssWidth,cssHeight);const final=imageCache.get(imageUrl(target.image));if(final instanceof Promise)final.then(img=>{if(canvas.isConnected){ctx.clearRect(0,0,cssWidth,cssHeight);drawPerk(ctx,img,0,0,cssWidth,cssHeight)}});canvas.dataset.spinning='false';return}requestAnimationFrame(frame)}requestAnimationFrame(frame)}

  function killerEntries(pool){const out=[];(pool||[]).forEach(k=>{if(!k?.image||Number(k.weight)<=0)return;const donors=Array.isArray(k.donors)?k.donors.filter(Boolean):[];out.push({killer:k,donor:null,id:k.key+':base'});donors.forEach((d,i)=>out.push({killer:k,donor:d,id:k.key+':donor:'+i}));for(let i=0;i<Math.max(0,Math.floor(Number(k.weight)||1)-1-donors.length);i++)out.push({killer:k,donor:null,id:k.key+':extra:'+i})});return out}
  function noAdjacent(source,previous=null){const pool=[...source],out=[];let prev=previous;while(pool.length){const choices=[];for(let i=0;i<pool.length;i++)if(pool[i].killer.key!==prev)choices.push(i);const pick=choices.length?choices[Math.floor(Math.random()*choices.length)]:Math.floor(Math.random()*pool.length),e=pool.splice(pick,1)[0];out.push(e);prev=e.killer.key}return out}
  function longDeck(entries,min){const out=[];let prev=null;while(out.length<min){const batch=noAdjacent(entries,prev);out.push(...batch);prev=out.length?out[out.length-1].killer.key:null}return out.slice(0,Math.max(min,entries.length*8))}
  function killerCard(entry){const c=document.createElement('div');c.className='sl-killer-card'+(entry.donor?' donated':'');c.dataset.key=entry.killer.key;c.dataset.entryId=entry.id||entry.killer.key;const frame=document.createElement('img');frame.className='sl-killer-card-frame';frame.src='../rectangulo-fondo.png';frame.alt='';const img=document.createElement('img');img.className='sl-killer-card-portrait';img.src=imageUrl(entry.killer.image);img.alt=entry.killer.name||'';img.draggable=false;const name=document.createElement('div');name.className='sl-killer-card-name';name.textContent=entry.killer.name==='Jason (El Destripador)'?'Jason':entry.killer.name;c.append(frame,img,name);if(entry.donor){const d=document.createElement('div');d.className='sl-killer-card-donor';d.textContent=entry.donor;c.appendChild(d)}return c}
  function killerStep(track){const first=track.firstElementChild;return(first?parseFloat(getComputedStyle(first).width):196)+14}
  function killerOffset(track,index){const s=killerStep(track);return -(index*s+(s-14)/2)}
  function centerKiller(track,index){track.getAnimations().forEach(a=>a.cancel());track.style.transition='none';track.style.transform=`translate3d(${killerOffset(track,index)}px,-50%,0)`}
  function renderKillerDeck(track,deck){track.replaceChildren(...deck.map(killerCard))}
  function staticKiller(track,pool,winner=null){const entries=killerEntries(pool);if(!entries.length){track.replaceChildren();return}let deck=longDeck(entries,Math.max(18,entries.length*3)),index=Math.min(6,deck.length-1);if(winner){const replacement={killer:{...winner,weight:1,donors:winner.donor?[winner.donor]:[]},donor:winner.donor||null,id:winner.key+':winner'};if(deck.length<7)while(deck.length<7)deck.push(...noAdjacent(entries,deck.at(-1)?.killer?.key||null));index=Math.min(6,deck.length-1);deck[index]=replacement}renderKillerDeck(track,deck);centerKiller(track,index);if(winner&&track.children[index])track.children[index].classList.add('selected')}
  function spinKiller(target,track,pool,winner,spinId,duration=8000){const entries=killerEntries(pool);if(entries.length<2||!winner){staticKiller(track,pool,winner);return}const deck=longDeck(entries,Math.max(100,entries.length*10)),start=5,targetIndex=deck.length-7;deck[targetIndex]={killer:{...winner,weight:1,donors:winner.donor?[winner.donor]:[]},donor:winner.donor||null,id:winner.key+':winner'};renderKillerDeck(track,deck);const sx=killerOffset(track,start),ex=killerOffset(track,targetIndex);track.style.transition='none';track.style.transform=`translate3d(${sx}px,-50%,0)`;track.getBoundingClientRect();const anim=track.animate([{transform:`translate3d(${sx}px,-50%,0)`,offset:0},{transform:`translate3d(${sx+(ex-sx)*.72}px,-50%,0)`,offset:.60},{transform:`translate3d(${sx+(ex-sx)*.92}px,-50%,0)`,offset:.84},{transform:`translate3d(${ex}px,-50%,0)`,offset:1}],{duration,easing:'cubic-bezier(.12,.72,.16,1)',fill:'forwards'});target._slKillerSpin={spinId,anim,track,targetIndex,ex,winner};anim.finished.then(()=>{if(!track.isConnected)return;track.style.transform=`translate3d(${ex}px,-50%,0)`;anim.cancel();const card=track.children[targetIndex];if(card)card.classList.add('selected');if(target._slKillerSpin?.spinId===spinId)target._slKillerSpin.finished=true}).catch(()=>{})}
  function paintKiller(target,data){const state=data?.state||{},pool=state.spinPool||data?.settings?.pool||[],winner=(state.targets||[])[0]||(state.items||[])[0]||null;target.innerHTML='<div class="sl-killer-web"><div class="sl-killer-web-reel"><div class="sl-killer-track"></div><div class="sl-killer-edge sl-killer-edge-left"></div><div class="sl-killer-edge sl-killer-edge-right"></div><div class="sl-killer-marker sl-killer-marker-top"></div><div class="sl-killer-marker sl-killer-marker-bottom"></div></div></div>';const track=target.querySelector('.sl-killer-track');if(state.status==='spinning')spinKiller(target,track,pool,winner,state.spinId||'',Number(state.durationMs)||8000);else staticKiller(track,pool,state.status==='result'?winner:null)}

  function paintPerks(target,data){const state=data?.state||{},pool=data?.settings?.pool||[],spinning=state.status==='spinning',result=state.status==='result',items=state.items||[],targets=state.targets||[],chaotic=state.cardRule?.event==='chaotic',slots=4,active=spinning?(state.activeSlots||[0,1,2,3]):[];target.innerHTML=`<div class="sl-roulette${spinning?' is-spinning':''}${result?' is-result':''}${chaotic?' is-chaotic':''}"><div class="sl-roulette-slots">${Array.from({length:slots},(_,i)=>{if(spinning){const fixed=items[i]||null;if(active.includes(i))return `<article class="sl-roulette-slot is-rolling"><div class="sl-roulette-roll-shell"><canvas class="sl-roulette-canvas" data-slot="${i}"></canvas></div><div class="sl-roulette-label-space"></div></article>`;return `<article class="sl-roulette-slot${fixed?' is-result-slot':''}${!fixed?' is-inactive':''}">${itemMarkup(fixed)}</article>`}const item=items[i]||null;return `<article class="sl-roulette-slot${result&&item?' is-result-slot':''}${item?.donor?' has-donor':''}${!item?' is-inactive':''}">${itemMarkup(item)}</article>`}).join('')}</div></div>`;if(spinning)target.querySelectorAll('.sl-roulette-canvas').forEach(canvas=>{const i=Number(canvas.dataset.slot),targetItem=targets[i];if(targetItem)animatePerkCanvas(canvas,pool,targetItem,i*140)})}
  function render(target,data,{preview=false}={}){const state=data?.state||{},killer=data?.kind==='roulette_killers',items=state.items||[],targets=state.targets||[],pool=state.spinPool||data?.settings?.pool||[],signature=JSON.stringify([data.kind,state.status,state.visible,state.spinId,items.map(x=>x?.key),targets.map(x=>x?.key),state.activeSlots,state.cardRule?.resultId,state.cardRule?.event,pool.map(x=>x.key)]);if(!preview&&state.visible===false){target.dataset.rouletteSignature=signature;target.innerHTML='';target._slKillerSpin=null;return}if(killer&&state.status==='result'&&state.spinId&&target._slKillerSpin?.spinId===state.spinId){target.dataset.rouletteSignature=signature;return}if(target.dataset.rouletteSignature===signature)return;target.dataset.rouletteSignature=signature;killer?paintKiller(target,data):paintPerks(target,data)}
  window.SanLeanRouletteView={render};
})();