(()=>{if(!window.gtag){const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id=G-0VBRTF7W0R';document.head.appendChild(s);window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};gtag('js',new Date());gtag('config','G-0VBRTF7W0R')}})();

(()=>{
  const cfg = window.SANLEAN_SUPABASE;
  if (!cfg || !window.supabase) return;
  const SIM_KEY='sanlean-roulette-simulation-v1';
  const client = window.supabase.createClient(cfg.url, cfg.publishableKey, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  window.sanleanSupabase=client;
  let syncing=false,saveTimer=null,currentProfile=null;
  const normalizeUsername=v=>String(v||'').trim().toLowerCase();
  const validUsername=v=>/^[a-z0-9_-]{3,30}$/.test(v);
  const api=window.SanLeanAccount={
    async session(){return (await client.auth.getSession()).data.session}, async signIn(email,password){return client.auth.signInWithPassword({email,password})}, async signOut(){return client.auth.signOut()}, async resetPassword(email){return client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/Usuario/restablecer-contrasena.html'})}, async updatePassword(password){return client.auth.updateUser({password})},
    async loadProfile(){const s=await api.session();if(!s)return null;const {data,error}=await client.from('user_profiles').select('first_name,last_name,username,role,onboarding_completed').eq('user_id',s.user.id).maybeSingle();if(error)throw error;if(data)return data;const {data:created,error:createError}=await client.from('user_profiles').insert({user_id:s.user.id,role:'owner'}).select('first_name,last_name,username,role,onboarding_completed').single();if(createError)throw createError;return created},
    async saveProfile(firstName,lastName,username,onboardingCompleted){const s=await api.session();if(!s)throw new Error('Sin sesión');const cleanUsername=normalizeUsername(username);if(!validUsername(cleanUsername)){const err=new Error('Nombre de usuario inválido');err.code='USERNAME_INVALID';throw err}const payload={user_id:s.user.id,first_name:firstName.trim(),last_name:lastName.trim(),username:cleanUsername};if(typeof onboardingCompleted==='boolean')payload.onboarding_completed=onboardingCompleted;const {data,error}=await client.from('user_profiles').upsert(payload,{onConflict:'user_id'}).select('first_name,last_name,username,role,onboarding_completed').single();if(error)throw error;currentProfile=data;return data},
    async loadSettings(){const s=await api.session();if(!s)return null;const {data,error}=await client.from('user_roulette_settings').select('settings').eq('user_id',s.user.id).maybeSingle();if(error)throw error;return data?.settings||{weights:{},bonusEntries:{}}}, async saveSettings(settings){const s=await api.session();if(!s)return;const clean={weights:settings?.weights||{},bonusEntries:settings?.bonusEntries||{}};const {error}=await client.from('user_roulette_settings').upsert({user_id:s.user.id,settings:clean},{onConflict:'user_id'});if(error)throw error}, async syncToBrowser(){const settings=await api.loadSettings();if(!settings)return false;syncing=true;localStorage.setItem(SIM_KEY,JSON.stringify({...settings,updatedAt:Date.now(),source:'supabase'}));syncing=false;return true}, onAuthChange(callback){return client.auth.onAuthStateChange(callback)}
  };
  const nativeSet=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){nativeSet.call(this,key,value);if(this===localStorage&&key===SIM_KEY&&!syncing){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{try{await api.saveSettings(JSON.parse(value))}catch(err){console.error('SanLean Supabase save:',err)}},180)}};
  function msg(text,isError=false){const el=document.getElementById('loginMessage');if(el){el.textContent=text||'';el.classList.toggle('error',!!isError)}}
  function installAccountMenuStyles(){if(document.querySelector('link[data-sanlean-account-menu]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='../css/usuario-account-menu.css';link.dataset.sanleanAccountMenu='true';document.head.appendChild(link)}
  function setAccountMenu(open){const trigger=document.getElementById('accountIdentityTrigger'),menu=document.getElementById('accountIdentityDropdown');if(!trigger||!menu)return;trigger.setAttribute('aria-expanded',open?'true':'false');menu.hidden=!open}
  function renderAccountMenu(session,profile){const actions=document.querySelector('.account-actions');if(!actions)return;const identity=profile?.username||session?.user?.email||'CUENTA';actions.innerHTML=`<div class="user-account-menu"><button id="accountIdentityTrigger" class="user-account-trigger" type="button" aria-expanded="false" aria-controls="accountIdentityDropdown"><span class="account-identity-text"></span><span class="account-chevron" aria-hidden="true"></span></button><div id="accountIdentityDropdown" class="user-account-dropdown" hidden><a href="./cuenta.html">MI CUENTA</a><button id="demoLogout" class="account-menu-danger" type="button">CERRAR SESIÓN</button></div></div>`;actions.querySelector('.account-identity-text').textContent=identity}
  function ensureOnboardingUsername(){const data=document.querySelector('#onboardingModal .profile-data');if(!data||document.getElementById('onboardingUsername'))return;const emailLabel=data.querySelector('.profile-email-field');const label=document.createElement('label');label.innerHTML='NOMBRE DE USUARIO<input id="onboardingUsername" type="text" maxlength="30" autocomplete="username" placeholder="ej. sanlean17"><small class="username-help">3 a 30 caracteres. Usá letras minúsculas, números, guion o guion bajo.</small>';data.insertBefore(label,emailLabel||null);label.querySelector('input').addEventListener('input',e=>{e.target.value=normalizeUsername(e.target.value)})}
  function fillProfile(session,profile){const email=session?.user?.email||'';['profileEmail','onboardingEmail'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=email});const n=document.getElementById('profileName'),s=document.getElementById('profileSurname'),u=document.getElementById('profileUsername'),ou=document.getElementById('onboardingUsername');if(n)n.value=profile?.first_name||'';if(s)s.value=profile?.last_name||'';if(u)u.value=profile?.username||'';if(ou)ou.value=profile?.username||'';renderAccountMenu(session,profile)}
  function setProfileEditing(editing){const n=document.getElementById('profileName'),s=document.getElementById('profileSurname'),u=document.getElementById('profileUsername'),b=document.getElementById('profileEdit'),toggle=document.getElementById('togglePassword'),box=document.getElementById('passwordBox'),out=document.getElementById('profileSaveMessage');if(n)n.readOnly=!editing;if(s)s.readOnly=!editing;if(u)u.readOnly=!editing;if(b){b.textContent=editing?'GUARDAR':'EDITAR';b.hidden=false}if(toggle)toggle.hidden=editing;if(box)box.hidden=true;if(out)out.textContent=''}
  function setPasswordMode(open){const box=document.getElementById('passwordBox'),toggle=document.getElementById('togglePassword'),edit=document.getElementById('profileEdit'),profileMsg=document.getElementById('profileSaveMessage'),passwordMsg=document.getElementById('passwordMessage');if(box)box.hidden=!open;if(toggle)toggle.hidden=open;if(edit)edit.hidden=open;if(profileMsg)profileMsg.textContent='';if(passwordMsg)passwordMsg.textContent='';if(open){const n=document.getElementById('profileName'),s=document.getElementById('profileSurname'),u=document.getElementById('profileUsername');if(n)n.readOnly=true;if(s)s.readOnly=true;if(u)u.readOnly=true;setTimeout(()=>document.getElementById('newPassword')?.focus(),20)}}
  function installUiFixes(){installAccountMenuStyles();ensureOnboardingUsername();const style=document.createElement('style');style.textContent='#onboardingModal #completeOnboarding{margin-top:32px!important}#onboardingModal .username-help{display:block;margin-top:8px;color:rgba(255,255,255,.55);font:500 11px/1.5 Montserrat,Arial,sans-serif}#profileEdit{display:block;margin:12px 0 0 auto;padding:0;border:0;background:transparent;color:#ff003c;font:800 12px Montserrat,Arial,sans-serif;cursor:pointer}#profileEdit[hidden]{display:none!important}#profileName[readonly],#profileSurname[readonly],#profileUsername[readonly],#profileEmail[readonly]{color:rgba(255,255,255,.72);cursor:default}#profileModal .profile-dialog{width:min(560px,100%)}#profileModal .change-password-toggle{display:block;width:auto;min-width:210px;height:44px;margin:28px auto 0;padding:0 28px}#profileModal .change-password-toggle[hidden]{display:none!important}#profileModal .save-password-wrap{margin-top:26px}#profileModal .save-password-wrap button{width:auto;min-width:205px;padding:0 28px}#profileModal .close-profile-btn{display:block;width:auto;min-width:150px;margin:30px auto 0;padding:0 30px}#profileModal .profile-message:empty{display:none}#profileModal .password-box{padding-top:30px}.recovery-email-dialog{width:min(540px,100%)}.recovery-email-dialog h2{line-height:1.05;margin-bottom:24px}.recovery-email-label{display:block;font-size:11px;font-weight:800}.recovery-email-label input{margin-top:9px}.recovery-send-btn{width:100%;margin-top:26px}.recovery-cancel-btn{margin-top:14px;background:transparent;border:1px solid #ff003c}.recovery-email-dialog .profile-message{line-height:1.5}';document.head.appendChild(style);const old=document.getElementById('saveProfile');if(old){const edit=document.createElement('button');edit.id='profileEdit';edit.type='button';edit.textContent='EDITAR';old.replaceWith(edit)}const n=document.getElementById('profileName'),s=document.getElementById('profileSurname'),u=document.getElementById('profileUsername');if(n)n.readOnly=true;if(s)s.readOnly=true;if(u)u.readOnly=true}
  function openOnboarding(session,profile){fillProfile(session,profile);const modal=document.getElementById('onboardingModal');if(modal){modal.hidden=false;document.body.classList.add('onboarding-required')}} function closeOnboarding(){const modal=document.getElementById('onboardingModal');if(modal)modal.hidden=true;document.body.classList.remove('onboarding-required')}
  async function showPanel(session){const login=document.getElementById('loginView'),panel=document.getElementById('panelView');if(login)login.hidden=true;if(panel)panel.hidden=false;try{currentProfile=await api.loadProfile();fillProfile(session,currentProfile);if(!currentProfile?.onboarding_completed){openOnboarding(session,currentProfile);return}}catch(err){console.error('Profile load:',err);renderAccountMenu(session,currentProfile)}closeOnboarding();setTimeout(()=>{const active=document.querySelector('.panel-tabs button.active');if(active)active.click()},0)} function showLogin(){const login=document.getElementById('loginView'),panel=document.getElementById('panelView');if(panel)panel.hidden=true;if(login)login.hidden=false;closeOnboarding()}
  document.addEventListener('submit',async e=>{if(e.target?.id!=='demoLogin')return;e.preventDefault();e.stopImmediatePropagation();const email=document.getElementById('loginEmail')?.value.trim(),password=document.getElementById('loginPassword')?.value||'';msg('INGRESANDO...');const {data,error}=await api.signIn(email,password);if(error){msg('No se pudo iniciar sesión. Revisá el correo y la contraseña.',true);return}try{await api.syncToBrowser()}catch(err){console.error(err);msg('La cuenta ingresó, pero no se pudo cargar MI PANEL.',true);return}msg('');await showPanel(data.session)},true);
  document.addEventListener('click',async e=>{
    const identity=e.target.closest?.('#accountIdentityTrigger');if(identity){e.preventDefault();e.stopPropagation();setAccountMenu(document.getElementById('accountIdentityDropdown')?.hidden??true);return}
    if(!e.target.closest?.('.user-account-menu'))setAccountMenu(false);
    const profileOpen=e.target.closest?.('#profileBtn');if(profileOpen){setTimeout(async()=>{const session=await api.session();if(!currentProfile)currentProfile=await api.loadProfile();fillProfile(session,currentProfile);setProfileEditing(false);setPasswordMode(false)},0)}
    const edit=e.target.closest?.('#profileEdit');if(edit){e.preventDefault();e.stopImmediatePropagation();const n=document.getElementById('profileName'),s=document.getElementById('profileSurname'),u=document.getElementById('profileUsername'),out=document.getElementById('profileSaveMessage');if(n.readOnly){setProfileEditing(true);n.focus();return}const name=n.value.trim(),surname=s.value.trim(),username=normalizeUsername(u?.value||currentProfile?.username||'');if(!name||!surname){out.textContent='Completá nombre y apellido.';return}if(!validUsername(username)){out.textContent='El nombre de usuario debe tener entre 3 y 30 caracteres y usar sólo letras minúsculas, números, guion o guion bajo.';return}try{currentProfile=await api.saveProfile(name,surname,username,currentProfile?.onboarding_completed??true);const session=await api.session();fillProfile(session,currentProfile);setProfileEditing(false);out.textContent='Perfil actualizado correctamente.'}catch(err){console.error(err);out.textContent=err.code==='23505'?'Ese nombre de usuario ya está en uso. Elegí otro.':'No se pudo actualizar el perfil.'}return}
    const toggle=e.target.closest?.('#togglePassword');if(toggle){e.preventDefault();e.stopImmediatePropagation();setPasswordMode(true);return}
    const logout=e.target.closest?.('#demoLogout');if(logout){e.preventDefault();e.stopImmediatePropagation();await api.signOut();localStorage.removeItem(SIM_KEY);setAccountMenu(false);showLogin();return}
    const forgot=e.target.closest?.('#forgotPassword');if(forgot){e.preventDefault();e.stopImmediatePropagation();msg('');const modal=document.getElementById('forgotPasswordModal'),input=document.getElementById('recoveryEmail'),out=document.getElementById('recoveryEmailMessage');if(input)input.value=document.getElementById('loginEmail')?.value.trim()||'';if(out){out.textContent='';out.className='profile-message'}if(modal)modal.hidden=false;setTimeout(()=>input?.focus(),30);return}
    const closeRecovery=e.target.closest?.('#closeRecoveryEmail');if(closeRecovery){e.preventDefault();document.getElementById('forgotPasswordModal').hidden=true;return}
    const sendRecovery=e.target.closest?.('#sendRecoveryEmail');if(sendRecovery){e.preventDefault();e.stopImmediatePropagation();const input=document.getElementById('recoveryEmail'),out=document.getElementById('recoveryEmailMessage'),email=input?.value.trim()||'';out.className='profile-message';if(!email||!input.checkValidity()){out.textContent='Ingresá un correo electrónico válido.';out.classList.add('error');return}sendRecovery.disabled=true;sendRecovery.textContent='ENVIANDO...';out.textContent='';const {error}=await api.resetPassword(email);if(error){console.error('Password recovery:',error);out.textContent='No se pudo enviar el correo de recuperación. Volvé a intentarlo en unos minutos.';out.classList.add('error')}else{out.textContent='Si el correo está registrado, te enviaremos un enlace para cambiar tu contraseña. Revisá también Spam o Correo no deseado.'}sendRecovery.disabled=false;sendRecovery.textContent='ENVIAR';return}
    const complete=e.target.closest?.('#completeOnboarding');if(complete){e.preventDefault();e.stopImmediatePropagation();const name=document.getElementById('onboardingName')?.value.trim()||'',surname=document.getElementById('onboardingSurname')?.value.trim()||'',username=normalizeUsername(document.getElementById('onboardingUsername')?.value||''),a=document.getElementById('onboardingPassword')?.value||'',b=document.getElementById('onboardingRepeatPassword')?.value||'',out=document.getElementById('onboardingMessage');if(!name||!surname){out.textContent='Completá nombre y apellido.';return}if(!validUsername(username)){out.textContent='Elegí un nombre de usuario de 3 a 30 caracteres usando letras minúsculas, números, guion o guion bajo.';return}if(a.length<8){out.textContent='La nueva contraseña debe tener al menos 8 caracteres.';return}if(a!==b){out.textContent='Las contraseñas no coinciden.';return}complete.disabled=true;out.textContent='GUARDANDO...';const {error}=await api.updatePassword(a);if(error){out.textContent='No se pudo cambiar la contraseña.';complete.disabled=false;return}try{currentProfile=await api.saveProfile(name,surname,username,true);const session=await api.session();fillProfile(session,currentProfile);document.getElementById('onboardingPassword').value='';document.getElementById('onboardingRepeatPassword').value='';closeOnboarding();out.textContent='';setTimeout(()=>{const active=document.querySelector('.panel-tabs button.active');if(active)active.click()},0)}catch(err){console.error(err);out.textContent=err.code==='23505'?'Ese nombre de usuario ya está en uso. Elegí otro.':'La contraseña cambió, pero no se pudo guardar el perfil. Volvé a intentarlo.'}complete.disabled=false;return}
    const change=e.target.closest?.('#changePassword');if(change){e.preventDefault();e.stopImmediatePropagation();const a=document.getElementById('newPassword')?.value||'',b=document.getElementById('repeatPassword')?.value||'',out=document.getElementById('passwordMessage');if(a.length<8){if(out)out.textContent='La contraseña debe tener al menos 8 caracteres.';return}if(a!==b){if(out)out.textContent='Las contraseñas no coinciden.';return}const {error}=await api.updatePassword(a);if(out)out.textContent=error?'No se pudo cambiar la contraseña.':'Contraseña actualizada correctamente.';if(!error){document.getElementById('newPassword').value='';document.getElementById('repeatPassword').value=''}return}
  },true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')setAccountMenu(false);const modal=document.getElementById('forgotPasswordModal');if(!modal||modal.hidden)return;if(e.key==='Escape')modal.hidden=true;if(e.key==='Enter'&&document.activeElement?.id==='recoveryEmail'){e.preventDefault();document.getElementById('sendRecoveryEmail')?.click()}});
  window.addEventListener('DOMContentLoaded',async()=>{installUiFixes();const recoveryModal=document.getElementById('forgotPasswordModal');recoveryModal?.addEventListener('click',e=>{if(e.target===recoveryModal)recoveryModal.hidden=true});const session=await api.session();if(!session){showLogin();return}try{await api.syncToBrowser()}catch(err){console.error('SanLean Supabase load:',err)}await showPanel(session)});
})();