(()=>{
const killerNames={trapper:'trapper trampero evan macmillan',wraith:'wraith espectro philip ojomo',hillbilly:'hillbilly pueblerino max thompson',nurse:'nurse enfermera sally smithson',myers:'myers michael myers shape forma',hag:'hag bruja lisa sherwood',doctor:'doctor herman carter',huntress:'huntress cazadora anna',leatherface:'leatherface cannibal canibal bubba sawyer',freddy:'freddy nightmare pesadilla freddy krueger',pig:'pig cerda amanda young',clown:'clown payaso kenneth chase',spirit:'spirit espiritu rin yamaoka',legion:'legion frank julie susie joey',plague:'plague plaga adiris',ghostface:'ghost face ghostface cara fantasma danny johnson',demogorgon:'demogorgon demo',oni:'oni kazan yamaoka',deathslinger:'deathslinger arponero caleb quinn',pyramidhead:'pyramid head executioner verdugo',blight:'blight deterioro talbot grimes',twins:'twins gemelos charlotte victor deshayes',trickster:'trickster traicionero ji woon hak',nemesis:'nemesis t type',cenobite:'cenobite cenobita pinhead elliot spencer',artist:'artist artista carmina mora',onryo:'onryo sadako yamamura',dredge:'dredge draga',wesker:'wesker mastermind mente maestra albert wesker',knight:'knight caballero tarhos kovacs',skullmerchant:'skull merchant comerciante calaveras adriana imai',singularity:'singularity singularidad hux',xenomorph:'xenomorph xenomorfo alien',chucky:'chucky good guy charles lee ray',unknown:'unknown desconocido',vecna:'vecna lich liche',dracula:'dracula dark lord señor oscuro',houndmaster:'houndmaster adiestradora canina portia maye',ghoul:'ghoul kaneki ken kaneki',animatronic:'animatronic animatronico springtrap',krasue:'krasue',lich:'first el primero',jason:'jason voorhees slasher destripador',judgment:'judgment sentencia'};
const ownerRanges=[['ghost face ghostface danny johnson',57],['demogorgon demo',60],['oni kazan yamaoka',63],['deathslinger arponero caleb quinn',66],['pyramid head executioner verdugo',69],['blight deterioro talbot grimes',72],['twins gemelos charlotte victor',75],['trickster traicionero ji woon',78],['nemesis',81],['cenobite pinhead',84],['artist carmina mora',87],['onryo sadako',90],['dredge draga',93],['wesker mastermind',97],['knight caballero',100],['skull merchant comerciante calaveras',103],['singularity singularidad',106],['xenomorph xenomorfo alien',109],['chucky good guy',112],['unknown desconocido',115],['vecna lich liche',118],['dracula dark lord',121],['houndmaster adiestradora canina',124],['ghoul kaneki',127],['animatronic springtrap',130],['krasue',133],['first primero',136],['jason voorhees',139],['judgment sentencia',142]];
const earlyOwners={'00_aNursesCalling':'nurse enfermera','01_agitation':'trapper trampero','02_bamboozle':'clown payaso','03_barbecueAndChilli':'cannibal canibal leatherface bubba','04_beastOfPrey':'huntress cazadora','06_bloodWarden':'nightmare pesadilla freddy','07_bloodhound':'wraith espectro','08_brutalStrength':'trapper trampero','09_corruptIntervention':'plague plaga','10_coulrophobia':'clown payaso','11_darkDevotion':'plague plaga','13_discordance':'legion','14_distressing':'doctor','15_dyingLight':'shape myers michael','16_enduring':'hillbilly pueblerino','17_fireUp':'nightmare pesadilla freddy','18_franklinsDemise':'cannibal canibal leatherface bubba','19_hangmansTrick':'pig cerda amanda','20_hexDevourHope':'hag bruja','21_hexHauntedGround':'spirit espiritu','22_hexHuntressLullaby':'huntress cazadora','24_hexRuin':'hag bruja','25_hexTheThirdSeal':'hag bruja','27_infectiousFright':'plague plaga','29_ironGrasp':'trapper trampero','30_ironMaiden':'legion','31_knockOut':'cannibal canibal leatherface bubba','32_lightborn':'hillbilly pueblerino','33_madGrit':'legion','34_makeYourChoice':'pig cerda amanda','35_monitorAndAbuse':'doctor','37_overcharge':'doctor','38_overwhelmingPresence':'doctor','39_playWithYourFood':'shape myers michael','40_popGoesTheWeasel':'clown payaso','41_predator':'wraith espectro','42_rancor':'spirit espiritu','43_rememberMe':'nightmare pesadilla freddy','44_saveTheBestForLast':'shape myers michael','45_shadowborn':'wraith espectro','48_spiritFury':'spirit espiritu','49_stridor':'nurse enfermera','50_surveillance':'pig cerda amanda','51_territorialImperative':'huntress cazadora','52_thanatophobia':'nurse enfermera','53_tinkerer':'hillbilly pueblerino','54_unnervingPresence':'trapper trampero'};
function n(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/([a-z])([A-Z])/g,'$1 $2').toLowerCase().replace(/[_-]+/g,' ').replace(/[^a-z0-9ñ ]/g,' ').replace(/\s+/g,' ').trim()}function num(k){const m=String(k).match(/^(\d+)_/);return m?+m[1]:-1}function perkExtra(item){const k=item.key||'',i=num(k),a=[];if(earlyOwners[k])a.push(earlyOwners[k]);const g=ownerRanges.find(([,s])=>i>=s&&i<=s+2);if(g)a.push(g[0]);if(k.toLowerCase().includes('hex'))a.push('hex maleficio');if(k.includes('scourgeHook')||[86,89,91,126].includes(i))a.push('scourge hook gancho flagelante');return a.join(' ')}
function enrich(grid,items,type){if(!grid)return;grid.querySelectorAll('.config-item[data-key]').forEach(el=>{const item=items&&items.find(x=>x.key===el.dataset.key);const key=el.dataset.key;let extra='';if(type==='killer')extra=item?perkExtra(item):'';if(type==='killers')extra=killerNames[key]||key;el.dataset.search=n(`${el.dataset.search||''} ${extra}`)})}
const base=window.initConfigGrid;if(typeof base==='function')window.initConfigGrid=function(grid,items,type,disabled){base(grid,items,type,disabled);enrich(grid,items,type)};
Promise.all([fetch('data/killers.json').then(r=>r.json()).catch(()=>[]),fetch('data/perks-killer.json').then(r=>r.json()).catch(()=>[])]).then(([killers,perks])=>{enrich(document.getElementById('cfgKillersGrid'),killers,'killers');enrich(document.getElementById('cfgPerksGrid'),perks,'killer');enrich(document.getElementById('cfgGrid'),perks,'killer')});

// Ruleta de Killers: el engranaje debe funcionar aunque falle o tarde cualquier otra inicialización.
if(location.pathname.toLowerCase().includes('ruleta-killer')){
 document.addEventListener('click',e=>{
  const trigger=e.target.closest&&e.target.closest('#killerGearBtn,#cfgKillersToggle');
  if(!trigger)return;
  const gear=document.getElementById('killerGearBtn'),section=document.getElementById('killerConfigSection'),grid=document.getElementById('cfgKillersGrid'),toggle=document.getElementById('cfgKillersToggle');
  if(!gear||!section||!grid||!toggle)return;
  e.preventDefault();
  e.stopImmediatePropagation();
  const open=!section.classList.contains('gear-visible');
  section.classList.toggle('gear-visible',open);
  section.classList.toggle('open',open);
  grid.classList.toggle('open',open);
  gear.classList.toggle('active',open);
  gear.setAttribute('aria-expanded',String(open));
  toggle.classList.toggle('open',open);
  section.style.display=open?'block':'none';
  document.body.classList.toggle('config-open',open||!!document.querySelector('#perkConfigSection.gear-visible'));
  if(open)setTimeout(()=>section.scrollIntoView({behavior:'smooth',block:'start'}),60);
 },true);
}
})();