(()=>{
  const cfg=window.SANLEAN_SUPABASE,root=document.getElementById('obsOverlayRoot'),stage=document.getElementById('obsStage'),controls=document.getElementById('obsControl'),spinBtn=document.getElementById('obsSpin'),hideBtn=document.getElementById('obsHide'),token=new URLSearchParams(location.search).get('token')||'',endpoint=cfg?.url?`${cfg.url}/rest/v1/rpc`:'';let demoStarted=false,snapshot=null,busy=false,lastSignature='',lastVisible=false,lastKind='',transitionTimer=null,pendingRender=null;const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),isRoulette=kind=>['roulette_killers','roulette_killer_perks','roulette_survivor_perks'].includes(kind),isGoal=kind=>kind==='challenge_goal',isStreak=kind=>kind==='challenge_streak',isAllKillers=kind=>kind==='challenge_all_killers';
  let pollFailures=0;
  // These existing RPCs enforce the same per-overlay tokens as the Edge proxy.
  async function overlayRpc(name,body){
    const response=await fetch(endpoint+'/'+name,{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(12000)});
    if(!response.ok)throw new Error('Overlay request failed: '+response.status);
    return response.json();
  }
  async function postState(state){
    if(!snapshot?.canControl||!endpoint||!token)return false;
    try{return await overlayRpc('update_stream_overlay_by_control',{p_token:token,p_state:state})===true}catch{return false}
  }
  function visibility(data){if(isRoulette(data.kind))return data.state?.visible!==false&&data.state?.status!=='idle';if(data.kind==='vote')return data.state?.visible!==false&&Array.isArray(data.state?.cards)&&data.state.cards.length>0;if(data.kind==='giveaway')return data.state?.visible!==false;if(isGoal(data.kind))return data.state?.visible!==false&&['active','reached'].includes(data.state?.status);if(isStreak(data.kind))return data.state?.visible!==false&&data.state?.status==='active';if(isAllKillers(data.kind))return data.state?.visible!==false&&data.state?.status==='active';return false}
  function animatePresence(show,kind){if(kind==='vote'){root.classList.remove('obs-entering','obs-leaving');root.classList.toggle('obs-hidden',!show);lastVisible=show;lastKind=kind;return}if(show){root.classList.remove('obs-hidden','obs-leaving');if(!lastVisible){root.classList.remove('obs-entering');void root.offsetWidth;root.classList.add('obs-entering');setTimeout(()=>root.classList.remove('obs-entering'),850)}}else if(lastVisible){root.classList.remove('obs-entering');root.classList.add('obs-leaving');setTimeout(()=>{if(!visibility(snapshot)){root.classList.add('obs-hidden');root.classList.remove('obs-leaving')}},620)}else root.classList.add('obs-hidden');lastVisible=show;lastKind=kind}
  function renderRoulette(data){window.SanLeanRouletteView.render(stage,data)}function renderVote(data){const s=data.state||{};if(!Array.isArray(s.cards)||!s.cards.length){stage.innerHTML='';delete stage.dataset.cardsSignature;return}window.SanLeanCardsView.render(stage,s)}function renderGoal(data){window.SanLeanChallengeGoalView?.render(stage,data)}function renderStreak(data){window.SanLeanChallengeStreakView?.render(stage,data)}function renderAllKillers(data){window.SanLeanChallengeRosterView?.render(stage,data)}function renderGiveaway(data){const s=data.state||{};stage.innerHTML=`<div class="obs-giveaway-box"><div class="obs-giveaway-head"><h2>SORTEO</h2><strong>${escapeHtml(s.statusLabel||'ABIERTO')}</strong></div><div><span>PALABRA CLAVE</span><h3>${escapeHtml(s.keyword||'—')}</h3><p>PARTICIPANTES: <strong>${Number(s.count)||0}</strong></p></div></div>`}
  function paint(data){snapshot=data;root.classList.toggle('control-mode',!!data.canControl);controls.hidden=!data.canControl;spinBtn.hidden=true;const show=visibility(data);if(isRoulette(data.kind))renderRoulette(data);else if(data.kind==='vote')renderVote(data);else if(data.kind==='giveaway')renderGiveaway(data);else if(isGoal(data.kind))renderGoal(data);else if(isStreak(data.kind))renderStreak(data);else if(isAllKillers(data.kind))renderAllKillers(data);else stage.innerHTML='';animatePresence(show,data.kind)}
  function render(data){const changing=lastVisible&&lastKind&&lastKind!==data.kind&&visibility(data);if(changing){pendingRender=data;clearTimeout(transitionTimer);root.classList.remove('obs-entering');root.classList.add('obs-leaving');transitionTimer=setTimeout(()=>{const next=pendingRender;pendingRender=null;root.classList.add('obs-hidden');root.classList.remove('obs-leaving');lastVisible=false;if(next)paint(next)},620);return}paint(data)}
  async function refresh(){const demo=new URLSearchParams(location.search).get('demo');if(!token&&demo){if(demoStarted)return;demoStarted=true;}if(!token&&['killers','killer-perks','survivor-perks'].includes(demo)){const killer=demo==='killers',role=demo==='survivor-perks'?'survivor':'killer',file=killer?'killers':`perks-${role}`;fetch(`../data/${file}.json`).then(r=>r.json()).then(catalog=>{const pool=catalog.filter(x=>!x.emptySlot).map(x=>({...x,image:x.image?`../${x.image}`:`../${role}/${x.key}.png`})),kind=killer?'roulette_killers':role==='killer'?'roulette_killer_perks':'roulette_survivor_perks',show=()=>render({kind,canControl:false,settings:{pool},state:{visible:true,status:'result',spinId:'demo',items:pool.slice(0,killer?1:4)}});if(new URLSearchParams(location.search).get('spin')==='1'){const targets=pool.slice(0,killer?1:4);render({kind,canControl:false,settings:{pool},state:{visible:true,status:'spinning',items:[],targets,activeSlots:targets.map((_,i)=>i),spinId:'demo'}});setTimeout(show,killer?8000:3420)}else show()});return}if(!token&&['normal','chaotic'].includes(demo)){fetch('../data/cards-assets.json').then(r=>r.json()).then(manifest=>{const special=demo==='chaotic',reveal=new URLSearchParams(location.search).get('reveal')||'none',ids=special?['normal_4','survivor_no_mither_object_random','survivor_totems','survivor_zero_perks_addons','survivor_two_bad_one_good_random']:['normal_0','normal_1','normal_2','normal_3','normal_4'],labels=special?['4 PERKS','ME LA PELA + OBJETO DE OBSESIÓN + 2 RANDOM','BUILD DE TÓTEMS','0 PERKS + 0 ADDONS','2 MALAS + 1 BUENA + 1 RANDOM']:['0 PERKS','1 PERK','2 PERKS','3 PERKS','4 PERKS'];render({kind:'vote',canControl:false,state:{visible:true,special,state:'revealed',winner:reveal==='none'?null:'B',cards:ids.map((id,i)=>({letter:'ABCDE'[i],revealed:reveal==='all'||(reveal==='winner'&&i===1),label:labels[i],image:`../cartas/${(special?manifest.chaoticResults[id]:null)||manifest.results[id]}`}))}})});return}if(!token||!endpoint)return;try{const rows=await overlayRpc('get_stream_overlay_by_token',{p_token:token}),row=rows?.[0];if(!row){pollFailures=Math.min(pollFailures+1,6);animatePresence(false,lastKind);return}const data={overlayId:row.overlay_id,kind:row.kind,settings:row.settings||{},state:row.state||{},canControl:!!row.can_control,updatedAt:row.updated_at},sig=JSON.stringify([data.kind,data.state,data.settings,data.canControl]);pollFailures=0;if(sig!==lastSignature){lastSignature=sig;render(data)}else snapshot=data}catch{pollFailures=Math.min(pollFailures+1,6)}}
  hideBtn?.addEventListener('click',()=>{if(snapshot?.kind==='challenge_goal'||snapshot?.kind==='challenge_streak'||snapshot?.kind==='challenge_all_killers')postState({...snapshot.state,visible:false});else postState({visible:false,status:'idle',items:[]})});if(!token&&!new URLSearchParams(location.search).get('demo')){root.classList.add('obs-hidden');return}async function poll(){await refresh();if(!token)return;const delay=pollFailures?Math.min(30000,1000*2**pollFailures):500;setTimeout(poll,delay)}poll();
})();
