document.addEventListener('DOMContentLoaded',()=>{
const killerFiles=['K01_TheTrapper_Portrait.png','K02_TheWraith_Portrait.png','K03_TheHillbilly_Portrait.png','K04_TheNurse_Portrait.png','K05_TheHag_Portrait.png','K06_TheShape_Portrait.png','K07_TheDoctor_Portrait.png','K08_TheHuntress_Portrait.png','K09_TheCannibal_Portrait.png','K10_TheNightmare_Portrait.png','K11_ThePig_Portrait.png','K12_TheClown_Portrait.png','K13_TheSpirit_Portrait.png','K14_TheLegion_Portrait.png','K15_ThePlague_Portrait.png','K16_TheGhostface_Portrait.png','K17_TheDemogorgon_Portrait.png','K18_TheOni_Portrait.png','K19_TheDeathslinger_Portrait.png','K20_TheExecutioner_Portrait.png','K21_TheBlight_Portrait.png','K22_TheTwins_Portrait.png','K23_TheTrickster_Portrait.png','K24_TheNemesis_Portrait.png','K25_TheCenobite_Portrait.png','K26_TheArtist_Portrait.png','K27_TheOnryo_Portrait.png','K28_TheDredge_Portrait.png','K29_TheMasterMind_Portrait.png','K30_TheKnight_Portrait.png','K31_TheSkullMerchant_Portrait.png','K32_TheSingularity_Portrait.png','K33_TheXenomorph_Portrait.png','K34_TheYerkes_Portrait.png','K35_TheUnknown_Portrait.png','K36_TheLich_Portrait.png','K37_TheDracula_Portrait.png','K38_TheHoundmaster_Portrait.png','K39_TheGhoul_Portrait.png','K40_TheAnimatronic_Portrait.png','T_UI_K41_TheKrasue_Portrait.png','T_UI_K42_TheFirst_Portrait.png','T_UI_K43_TheSlasher_Portrait.png','T_UI_K44_TheJudgment_Portrait.png'];
const survivorFiles=['S01_DwightFairfield_Portrait.png','S02_MegThomas_Portrait.png','S03_ClaudetteMorel_Portrait.png','S04_JakePark_Portrait.png','S05_NeaKarlsson_Portrait.png','S06_LaurieStrode_Portrait.png','S07_AceVisconti_Portrait.png','S08_WilliamBillOverbeck_Portrait.png','S09_FengMin_Portrait.png','S10_DavidKing_Portrait.png','S11_QuentinSmith_Portrait.png','S12_DetectiveDavidTapp_Portrait.png','S13_KateDenson_Portrait.png','S14_AdamFrancis_Portrait.png','S15_JeffJohansen_Portrait.png','S16_JaneRomero_Portrait.png','S17_AshleyJWilliams_Portrait.png','S18_SteveHarrington_Portrait.png','T_UI_S19_NancyWheeler_Portrait.png','S20_YuiKimura_Portrait.png','S21_ZarinaKassir_Portrait.png','S22_CherylMason_Portrait.png','S23_FelixRichter_Portrait.png','S24_ElodieRakoto_Portrait.png','S25_YunJinLee_Portrait.png','S26_JillValentine_Portrait.png','S27_LeonSKennedy_Portrait.png','S28_MikaelaReid_Portrait.png','S29_JonahVasquez_Portrait.png','S30_YoichiAsakawa_Portrait.png','S31_HaddieKaur_Portrait.png','S32_AdaWong_Portrait.png','S33_RebeccaChambers_Portrait.png','S34_VittorioToscano_Portrait.png','S35_ThalitaLyra_Portrait.png','S36_RenatoLyra_Portrait.png','S37_GabrielSoma_Portrait.png','S38_NicolasCage_Portrait.png','S39_EllenRipley_Portrait.png','S40_AlanWake_Portrait.png','S41_SableWard_Portrait.png','S42_TheTroupe_Portrait.png','S43_LaraCroft_Portrait.png','S44_TrevorBelmont_Portrait.png','S45_TaurieCain_Portrait.png','S46_OrelaRose_Portrait.png','S47_RickGrimes_Portrait.png','S48_MichonneGrimes_Portrait.png','T_UI_S49_VeeBoonyasak_Portrait.png','T_UI_S50_DustinHenderson_Portrait.png','T_UI_S51_Eleven_Portrait.png','T_UI_S52_KwonTaeYoung_Portrait.png','T_UI_S53_ShaneWiigwaas_Portrait.webp','T_UI_S54_Aurora_Portrait.png'];
const pool=document.getElementById('tierPool');let dragged=null,currentType='killers';
function makeCard(src,id,type){const el=document.createElement('div');el.className='tier-card';el.draggable=true;el.dataset.id=id;el.dataset.type=type;const img=document.createElement('img');img.src=src;img.alt='Personaje de Dead by Daylight';img.draggable=false;el.appendChild(img);el.addEventListener('dragstart',e=>{dragged=el;el.classList.add('dragging');e.dataTransfer.effectAllowed='move'});el.addEventListener('dragend',()=>{el.classList.remove('dragging');dragged=null});return el}
function allCards(type){return [...document.querySelectorAll('.tier-card')].filter(c=>c.dataset.type===type)}
function renderPool(type){currentType=type;pool.replaceChildren();const cards=allCards(type);cards.forEach(c=>pool.appendChild(c));if(!cards.length){const files=type==='killers'?killerFiles:survivorFiles;const folder=type==='killers'?'assets/killers/':'survivors/';files.forEach((f,i)=>pool.appendChild(makeCard(folder+f,type+'-'+i,type)))}document.querySelectorAll('.tier-card').forEach(c=>{c.style.display=c.dataset.type===type?'':'none'})}
function bindZone(zone){zone.addEventListener('dragover',e=>{e.preventDefault();zone.classList.add('drag-over');const after=getAfter(zone,e.clientX,e.clientY);if(dragged){if(after)zone.insertBefore(dragged,after);else zone.appendChild(dragged)}});zone.addEventListener('dragleave',()=>zone.classList.remove('drag-over'));zone.addEventListener('drop',e=>{e.preventDefault();zone.classList.remove('drag-over')})}
function getAfter(zone,x,y){const cards=[...zone.querySelectorAll('.tier-card:not(.dragging)')].filter(c=>getComputedStyle(c).display!=='none');let best=null,bestDist=Infinity;for(const c of cards){const r=c.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,d=Math.hypot(x-cx,(y-cy)*2);if(d<bestDist&&((y<cy)||(Math.abs(y-cy)<r.height/2&&x<cx))){bestDist=d;best=c}}return best}
document.querySelectorAll('.tier-dropzone').forEach(bindZone);bindZone(pool);
renderPool('killers');
document.querySelectorAll('.tier-tab').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.type;if(type===currentType)return;document.querySelectorAll('.tier-tab').forEach(b=>b.classList.toggle('active',b===btn));document.querySelectorAll('.tier-card').forEach(c=>{if(c.parentElement!==pool)c.style.display=c.dataset.type===type?'':'none'});renderPool(type)}));
});