/* USUARIO > CARTAS — canonical live game flow. */
(()=>{
  const STORAGE_PLATFORM='sanlean-cards-platform';
  const STORAGE_PENDING='sanlean-cards-pending-roulette';
  const ASSET_MANIFEST_URL='../data/cards-assets.json';
  const LETTERS=['A','B','C','D','E'];
  const NORMAL_RESULTS=[0,1,2,3,4].map(count=>({id:`normal_${count}`,type:'normal',count,label:count===1?'1 PERK':`${count} PERKS`,rule:{kind:'count',count}}));
  // Product decision still pending. Keep null until the final automatic chance is approved.
  const CHAOS_PROBABILITY=null;
  const CHAOS_RESULTS={
    survivor:[
      {id:'survivor_totems',type:'chaos',label:'BUILD TEMÁTICA DE TÓTEMS',rule:{kind:'category',category:'totem',count:4}},
      {id:'survivor_auras',type:'chaos',label:'BUILD DE AURAS',rule:{kind:'category',category:'aura',count:4}},
      {id:'survivor_no_mither_empty_random',type:'chaos',label:'ME LA PELA + SLOT VACÍO + 2 PERKS ALEATORIAS',rule:{kind:'fixed_random',fixed:['30_noMither','slot_vacio'],random:2}},
      {id:'survivor_no_mither_object_random',type:'chaos',label:'ME LA PELA + OBJETO DE OBSESIÓN + 2 PERKS ALEATORIAS',rule:{kind:'fixed_random',fixed:['30_noMither','32_objectOfObsession'],random:2}},
      {id:'survivor_two_bad_one_good_random',type:'chaos',label:'2 MALAS + 1 BUENA + 1 ALEATORIA',rule:{kind:'quality_mix',weak:2,strong:1,random:1}},
      {id:'survivor_zero_perks_addons',type:'chaos',label:'0 PERKS + 0 ADDONS',rule:{kind:'no_loadout',count:0,noAddons:true}}
    ],
    killer:[
      {id:'killer_totems',type:'chaos',label:'BUILD TEMÁTICA DE TÓTEMS',rule:{kind:'category',category:'totem',count:4}},
      {id:'killer_auras',type:'chaos',label:'BUILD DE AURAS',rule:{kind:'category',category:'aura',count:4}},
      {id:'killer_obsession',type:'chaos',label:'BUILD DE OBSESIÓN',rule:{kind:'category',category:'obsession',count:4}},
      {id:'killer_two_bad_one_good_random',type:'chaos',label:'2 MALAS + 1 BUENA + 1 ALEATORIA',rule:{kind:'quality_mix',weak:2,strong:1,random:1}},
      {id:'killer_zero_perks_addons',type:'chaos',label:'0 PERKS + 0 ADDONS',rule:{kind:'no_loadout',count:0,noAddons:true}}
    ]
  };
  let timer=null,secondsLeft=30,round=null,assetManifest={basePath:'../cartas',fallback:'../rombo.png',results:{}};
  const $=id=>document.getElementById(id);
  const randomFloat=()=>{const r=new Uint32Array(1);crypto.getRandomValues(r);return r[0]/0x100000000};
  const shuffle=input=>{const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(randomFloat()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  const safeStorage={get(k,f=''){try{return localStorage.getItem(k)||f}catch{return f}},set(k,v){try{localStorage.setItem(k,v)}catch{}},remove(k){try{localStorage.removeItem(k)}catch{}}};

  async function loadAssetManifest(){try{const r=await fetch(ASSET_MANIFEST_URL,{cache:'no-store'});if(r.ok)assetManifest=await r.json()}catch(err){console.warn('CARTAS assets:',err)}}
  function assetFor(result){const file=assetManifest.results?.[result?.id];return file?`${assetManifest.basePath||'../cartas'}/${file}`:''}
  function injectCss(){if(document.querySelector('link[data-sanlean-cards]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='../css/usuario-cartas.css?v=20260926-2';link.dataset.sanleanCards='true';document.head.appendChild(link)}
  function renameSurface(){document.querySelectorAll('[data-section-key="votes"],[data-tab="votes"]').forEach(btn=>{if(btn.textContent!=='CARTAS')btn.textContent='CARTAS'});document.querySelectorAll('.account-page .permission-grid label').forEach(label=>{const span=label.querySelector('span');if(span?.textContent.trim()==='VOTACIONES')span.textContent='CARTAS'});document.querySelectorAll('.account-page .permission-tags span').forEach(span=>{if(span.textContent.trim()==='VOTACIONES')span.textContent='CARTAS'})}
  function segmented(id,name,options,value){return `<div class="cards-choice-field"><span class="cards-choice-label">${name}</span><div class="cards-segmented" role="group" aria-label="${name}">${options.map(([v,label])=>`<button type="button" data-segment-value="${v}" aria-pressed="${v===value?'true':'false'}">${label}</button>`).join('')}</div><input id="${id}" type="hidden" value="${value}"></div>`}

  function buildPanel(){
    const section=$('streamVotesPanel');if(!section||section.dataset.cardsUi==='true')return false;section.dataset.cardsUi='true';
    section.innerHTML=`<div class="stream-module-head"><p class="eyebrow">JUEGO EN STREAM</p><h2>CARTAS</h2><p>Generá cinco cartas ocultas para que el chat vote o para elegir manualmente.<br>El resultado se revela sólo cuando vos lo decidas.</p></div>
      <div class="cards-platform-box"><h3 class="cards-section-title">PLATAFORMA DE CARTAS</h3><div class="cards-fields"><label>PLATAFORMA<select id="cardsPlatform"><option value="twitch">TWITCH</option><option value="kick">KICK</option><option value="both">TWITCH + KICK</option></select></label></div><p class="cards-help">Esta elección queda guardada para las próximas rondas.</p></div>
      <div class="cards-round-box"><h3 class="cards-section-title">CONFIGURACIÓN DE LA RONDA</h3><div class="cards-choice-grid">${segmented('cardsMode','MODO DE ELECCIÓN',[['chat','CHAT'],['manual','MANUAL']],'chat')}${segmented('cardsRole','PRÓXIMA PARTIDA',[['survivor','SUPERVIVIENTE'],['killer','KILLER']],'survivor')}</div><div class="cards-actions"><button id="cardsStart" class="cards-primary" type="button">INICIAR VOTACIÓN</button></div><p id="cardsRoundStatus" class="cards-status"></p></div>
      <div class="cards-live-box"><h3 class="cards-section-title">CONTROL EN VIVO</h3><div id="cardsEventBadge" class="cards-event-badge">EVENTO CAÓTICO · VOTOS ACUMULATIVOS</div><div class="cards-metrics"><div class="cards-metric"><span>ESTADO</span><strong id="cardsState">SIN INICIAR</strong></div><div class="cards-metric"><span>TIEMPO</span><strong id="cardsTimer">00:30</strong></div><div class="cards-metric"><span>TOTAL DE VOTOS</span><strong id="cardsTotalVotes">0</strong></div></div></div>
      <div class="cards-board-box"><h3 class="cards-section-title">CARTAS</h3><div id="cardsStage" class="cards-stage"></div><div id="cardsVoteResults" class="cards-vote-results"></div><div class="cards-actions"><button id="cardsRevealWinner" class="cards-primary" type="button" disabled>REVELAR CARTA GANADORA</button><button id="cardsRepeat" class="cards-secondary" type="button" hidden>REPETIR VOTACIÓN</button><button id="cardsNewRound" class="cards-secondary" type="button" disabled>NUEVA RONDA</button></div><p id="cardsBoardStatus" class="cards-status"></p><p class="cards-preview-note">Las imágenes definitivas se leen automáticamente desde <strong>/cartas/</strong> cuando estén disponibles.</p></div>
      <div id="cardsResultBox" class="cards-result-box" hidden><h3 class="cards-section-title">RESULTADO DE LA RONDA</h3><div class="cards-result-summary"><strong id="cardsOfficialResult">—</strong><span id="cardsOfficialRole">—</span></div><div class="cards-actions"><button id="cardsContinue" class="cards-primary" type="button">CONTINUAR A LA RULETA</button></div></div>`;
    return true
  }

  function shouldBeChaotic(forceSpecial){if(typeof forceSpecial==='boolean')return forceSpecial;if(typeof CHAOS_PROBABILITY!=='number')return false;return randomFloat()<Math.max(0,Math.min(1,CHAOS_PROBABILITY))}
  function chaoticFive(role){const chaos=shuffle(CHAOS_RESULTS[role]||[]),normal=shuffle(NORMAL_RESULTS),all=shuffle([...normal,...chaos]),selected=[];for(const result of all){if(selected.some(x=>x.id===result.id))continue;selected.push(result);if(selected.length===5)break}if(!selected.some(x=>x.type==='chaos')&&chaos.length)selected[Math.floor(randomFloat()*selected.length)]=chaos[0];return shuffle(selected)}
  function makeRound(options={}){const role=options.role||$('cardsRole')?.value||'survivor',special=shouldBeChaotic(options.special),results=special?chaoticFive(role):shuffle(NORMAL_RESULTS);return{mode:options.mode||$('cardsMode')?.value||'chat',role,platform:$('cardsPlatform')?.value||'twitch',special,state:'ready',winner:null,revealed:new Set(),userVotes:new Map(),cards:LETTERS.map((letter,index)=>({letter,result:results[index],votes:0}))}}
  function setState(text){if($('cardsState'))$('cardsState').textContent=text}
  function setTimer(value){if($('cardsTimer'))$('cardsTimer').textContent=`00:${String(Math.max(0,value)).padStart(2,'0')}`}
  function setTimerText(text){if($('cardsTimer'))$('cardsTimer').textContent=text}
  function totalVotes(){return round?round.cards.reduce((s,c)=>s+c.votes,0):0}
  function resultLabel(result){return result?.label||'RESULTADO'}
  function snapshot(){if(!round)return null;return{mode:round.mode,role:round.role,platform:round.platform,special:round.special,state:round.state,winner:round.winner,secondsLeft,totalVotes:totalVotes(),cards:round.cards.map(c=>({letter:c.letter,votes:c.votes,revealed:round.revealed.has(c.letter),resultId:round.revealed.has(c.letter)?c.result.id:null,label:round.revealed.has(c.letter)?c.result.label:null,image:round.revealed.has(c.letter)?assetFor(c.result):null}))}}
  function emitState(){window.dispatchEvent(new CustomEvent('sanlean:cards-state',{detail:snapshot()}))}

  function renderVoteRows(){const box=$('cardsVoteResults');if(!box||!round)return;const total=totalVotes();if($('cardsTotalVotes'))$('cardsTotalVotes').textContent=String(total);box.innerHTML=round.cards.map(c=>{const percent=total?Math.round(c.votes/total*100):0;return `<div class="cards-vote-row${round.special?' is-special':''}"><b>${c.letter}</b><div class="cards-vote-track"><i style="width:${percent}%"></i></div><span class="cards-vote-meta">${c.votes} VOTOS · ${percent}%</span></div>`}).join('');emitState()}
  function cardMarkup(card){const classes=['game-card'];if(round?.special)classes.push('is-special');if(round?.winner===card.letter)classes.push('is-winner');if(round?.revealed.has(card.letter))classes.push('is-revealed');if(round?.state==='manual-choice'||(round?.state==='revealed'&&round?.winner!==card.letter))classes.push('is-clickable');const revealed=round?.revealed.has(card.letter),src=revealed?assetFor(card.result):'';const result= revealed?`${src?`<img class="game-card-art" src="${src}" alt="" onerror="this.remove()">`:''}<em>${resultLabel(card.result)}</em>`:'';return `<button type="button" class="${classes.join(' ')}" data-card="${card.letter}" aria-label="Carta ${card.letter}"><span class="game-card-letter">${card.letter}</span><span class="game-card-result">${result}</span></button>`}
  function renderCards(){const stage=$('cardsStage');if(!stage||!round)return;stage.innerHTML=round.cards.map(cardMarkup).join('');stage.querySelectorAll('[data-card]').forEach(btn=>btn.addEventListener('click',()=>onCardClick(btn.dataset.card)));renderVoteRows();$('cardsEventBadge')?.classList.toggle('is-visible',!!round.special);emitState()}
  function configureButton(){const start=$('cardsStart');if(start)start.textContent=$('cardsMode')?.value==='manual'?'GENERAR CARTAS':'INICIAR VOTACIÓN'}

  function resetRoundUi(){clearInterval(timer);timer=null;secondsLeft=30;round=makeRound();setState('SIN INICIAR');if($('cardsMode')?.value==='manual')setTimerText('—');else setTimer(30);if($('cardsTotalVotes'))$('cardsTotalVotes').textContent='0';if($('cardsRevealWinner'))$('cardsRevealWinner').disabled=true;if($('cardsNewRound'))$('cardsNewRound').disabled=true;if($('cardsRepeat'))$('cardsRepeat').hidden=true;if($('cardsResultBox'))$('cardsResultBox').hidden=true;if($('cardsRoundStatus'))$('cardsRoundStatus').textContent='';if($('cardsBoardStatus'))$('cardsBoardStatus').textContent='';renderCards();configureButton()}
  function startChatRound(options={}){round=makeRound({mode:'chat',...options});round.state='active';secondsLeft=30;setState('VOTACIÓN ACTIVA');setTimer(secondsLeft);$('cardsRoundStatus').textContent=round.special?'EVENTO CAÓTICO activo: cada mensaje válido A–E suma un voto.':'Evento normal: cada usuario mantiene un único voto activo y puede cambiarlo.';$('cardsRevealWinner').disabled=true;$('cardsNewRound').disabled=true;$('cardsRepeat').hidden=true;$('cardsResultBox').hidden=true;renderCards();clearInterval(timer);timer=setInterval(()=>{secondsLeft-=1;setTimer(secondsLeft);emitState();if(secondsLeft<=0)finishChatRound()},1000)}
  function repeatChatRound(){if(!round)return;round.cards.forEach(c=>c.votes=0);round.userVotes=new Map();round.winner=null;round.revealed=new Set();round.state='active';secondsLeft=30;setState('VOTACIÓN ACTIVA');setTimer(30);$('cardsRevealWinner').disabled=true;$('cardsNewRound').disabled=true;$('cardsRepeat').hidden=true;$('cardsBoardStatus').textContent='Se repite la votación con las mismas cinco cartas.';renderCards();clearInterval(timer);timer=setInterval(()=>{secondsLeft-=1;setTimer(secondsLeft);emitState();if(secondsLeft<=0)finishChatRound()},1000)}
  function finishChatRound(){if(!round)return;clearInterval(timer);timer=null;secondsLeft=0;setTimer(0);const max=Math.max(...round.cards.map(c=>c.votes)),leaders=round.cards.filter(c=>c.votes===max);if(max>0&&leaders.length===1){round.winner=leaders[0].letter;round.state='awaiting-reveal';setState('ESPERANDO REVELACIÓN');$('cardsRevealWinner').disabled=false;$('cardsNewRound').disabled=false;$('cardsRepeat').hidden=true;$('cardsBoardStatus').textContent=`Ganó la carta ${round.winner}. El resultado sigue oculto hasta que lo reveles.`}else{round.state='tie';setState(max===0?'SIN VOTOS':'EMPATE');$('cardsNewRound').disabled=false;$('cardsRepeat').hidden=max===0;$('cardsBoardStatus').textContent=max===0?'La ronda terminó sin votos. Podés iniciar una nueva ronda.':'La ronda terminó empatada. Repetí la votación con estas mismas cinco cartas.'}renderCards()}
  function startManualRound(options={}){round=makeRound({mode:'manual',...options});round.state='manual-choice';setState('ELECCIÓN MANUAL');setTimerText('—');$('cardsRevealWinner').disabled=true;$('cardsNewRound').disabled=false;$('cardsRepeat').hidden=true;$('cardsResultBox').hidden=true;$('cardsRoundStatus').textContent=round.special?'Se generó un EVENTO CAÓTICO. Elegí una carta sin conocer su resultado.':'Elegí una carta. Seleccionarla no revela el resultado automáticamente.';$('cardsBoardStatus').textContent='TOCÁ UNA CARTA PARA ELEGIRLA';renderCards()}
  function registerVote(userId,letter){if(!round||round.mode!=='chat'||round.state!=='active')return false;const normalized=String(letter||'').trim().toUpperCase(),card=round.cards.find(c=>c.letter===normalized);if(!card)return false;if(round.special){card.votes+=1}else{const voter=String(userId||'').trim();if(!voter)return false;const previous=round.userVotes.get(voter);if(previous===normalized)return true;if(previous){const old=round.cards.find(c=>c.letter===previous);if(old)old.votes=Math.max(0,old.votes-1)}card.votes+=1;round.userVotes.set(voter,normalized)}renderVoteRows();return true}
  function registerChatMessage({platform,userId,message}={}){if(!round||round.mode!=='chat'||round.state!=='active')return false;const selected=round.platform||'both',incoming=String(platform||'').toLowerCase();if(selected!=='both'&&incoming&&incoming!==selected)return false;const match=String(message||'').trim().toUpperCase().match(/^([A-E])$/);return match?registerVote(userId,match[1]):false}
  function onCardClick(letter){if(!round)return;if(round.state==='manual-choice'){round.winner=letter;round.state='awaiting-reveal';setState('ESPERANDO REVELACIÓN');$('cardsRevealWinner').disabled=false;$('cardsBoardStatus').textContent=`Elegiste la carta ${letter}. El resultado sigue oculto.`;renderCards();return}if(round.state==='revealed'&&round.winner!==letter){round.revealed.add(letter);renderCards()}}
  function pendingPayload(result){return{source:'cards',role:round.role,event:round.special?'chaotic':'normal',resultId:result.id,label:result.label,rule:result.rule,createdAt:new Date().toISOString(),consumed:false}}
  function revealWinner(){if(!round?.winner)return;round.revealed.add(round.winner);round.state='revealed';setState('REVELADA');renderCards();const winner=round.cards.find(c=>c.letter===round.winner),result=winner?.result,role=round.role==='killer'?'KILLER':'SUPERVIVIENTE';$('cardsOfficialResult').textContent=resultLabel(result);$('cardsOfficialRole').textContent=role;$('cardsResultBox').hidden=false;$('cardsNewRound').disabled=false;const continueBtn=$('cardsContinue'),zero=result?.rule?.count===0||result?.rule?.kind==='no_loadout';continueBtn.hidden=zero;if(zero){safeStorage.set(STORAGE_PENDING,JSON.stringify(pendingPayload(result)));$('cardsBoardStatus').textContent=result?.rule?.noAddons?'Esta partida se juega sin perks y sin addons. La regla queda registrada para esta partida.':'Esta partida se juega sin perks.'}else{continueBtn.disabled=false;continueBtn.textContent='CONTINUAR A LA RULETA';$('cardsBoardStatus').textContent='Cuando continúes, la regla se aplicará a un único giro y después se eliminará automáticamente.'}}
  async function continueToRoulette(){if(!round?.winner)return;const winner=round.cards.find(c=>c.letter===round.winner),result=winner?.result;if(!result)return;safeStorage.set(STORAGE_PENDING,JSON.stringify(pendingPayload(result)));const btn=$('cardsContinue');if(btn){btn.disabled=true;btn.textContent='PREPARANDO RULETA...'}const tools=window.SanLeanStreamTools;if(tools?.spinByRole){const ok=await tools.spinByRole(round.role);if(ok){$('cardsBoardStatus').textContent='Ruleta iniciada con la regla de la carta ganadora. La regla se consumirá al confirmar el resultado.';if(window.SanLeanUsuarioNavigation?.show)window.SanLeanUsuarioNavigation.show('overlays');return}}const key=round.role==='killer'?'killerPerks':'survivor';if(window.SanLeanUsuarioNavigation?.show)window.SanLeanUsuarioNavigation.show(key);else location.hash=`#${key}`;if(btn){btn.disabled=false;btn.textContent='CONTINUAR A LA RULETA'}}

  function installSegmented(hiddenId){const input=$(hiddenId);if(!input)return;const group=input.previousElementSibling;if(!group?.classList.contains('cards-segmented'))return;const buttons=[...group.querySelectorAll('[data-segment-value]')];const select=value=>{input.value=value;buttons.forEach(button=>button.setAttribute('aria-pressed',button.dataset.segmentValue===value?'true':'false'));input.dispatchEvent(new Event('change',{bubbles:true}))};buttons.forEach(button=>button.addEventListener('click',()=>select(button.dataset.segmentValue)))}
  function installEvents(){$('cardsPlatform').value=safeStorage.get(STORAGE_PLATFORM,'twitch');$('cardsPlatform').addEventListener('change',()=>safeStorage.set(STORAGE_PLATFORM,$('cardsPlatform').value));installSegmented('cardsMode');installSegmented('cardsRole');$('cardsMode').addEventListener('change',resetRoundUi);$('cardsRole').addEventListener('change',resetRoundUi);$('cardsStart').addEventListener('click',()=>{$('cardsMode').value==='manual'?startManualRound():startChatRound()});$('cardsRevealWinner').addEventListener('click',revealWinner);$('cardsRepeat').addEventListener('click',repeatChatRound);$('cardsNewRound').addEventListener('click',resetRoundUi);$('cardsContinue').addEventListener('click',continueToRoulette)}
  async function install(){injectCss();renameSurface();await loadAssetManifest();if(!buildPanel())return;installEvents();resetRoundUi();window.SanLeanCards={registerVote,registerChatMessage,getRound:()=>round,getSnapshot:snapshot,startNormal:()=>($('cardsMode')?.value==='manual'?startManualRound({special:false}):startChatRound({special:false})),startChaotic:()=>($('cardsMode')?.value==='manual'?startManualRound({special:true}):startChatRound({special:true})),pendingKey:STORAGE_PENDING,chaosProbability:CHAOS_PROBABILITY,assetFor}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
