const sources={killers:{url:'../data/killers.json',img:'../killers'},survivor:{url:'../data/perks-survivor.json',img:'../survivor'},killerPerks:{url:'../data/perks-killer.json',img:'../killer'}};
const SIM_KEY='sanlean-roulette-simulation-v1';
let current='killers',items=[],weights={},bonusEntries={};
try{const saved=JSON.parse(localStorage.getItem(SIM_KEY)||'{}');weights=saved.weights||{};bonusEntries=saved.bonusEntries||{}}catch(e){}

const grid=document.getElementById('weightGrid');
const search=document.getElementById('panelSearch');
const roulettePanel=document.getElementById('roulettePanel');
const tournamentPanel=document.getElementById('tournamentPanel');
const streamPanels={overlays:document.getElementById('streamOverlaysPanel'),votes:document.getElementById('streamVotesPanel'),giveaways:document.getElementById('streamGiveawaysPanel'),platforms:document.getElementById('streamPlatformsPanel')};
const rouletteTabs=new Set(['killers','survivor','killerPerks']);
const allPanelKeys=new Set([...rouletteTabs,'tournament',...Object.keys(streamPanels)]);

function saveSimulation(){localStorage.setItem(SIM_KEY,JSON.stringify({weights,bonusEntries,updatedAt:Date.now()}))}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/([a-z])([A-Z])/g,'$1 $2').toLocaleLowerCase('es').replace(/[_-]+/g,' ').replace(/[^a-z0-9ñ ]/g,' ').replace(/\s+/g,' ').trim()}
const survivorOwners={'00_aceInTheHole':'ace visconti','33_open-Handed':'ace visconti','55_upTheAnte':'ace visconti','07_bond':'dwight fairfield','26_leader':'dwight fairfield','38_proveThyself':'dwight fairfield','01_adrenaline':'meg thomas','39_quickAndQuiet':'meg thomas','48_sprintBurst':'meg thomas','09_botanyKnowledge':'claudette morel','21_empathy':'claudette morel','42_selfCare':'claudette morel','11_calmSpirit':'jake park','24_ironWill':'jake park','41_saboteur':'jake park','05_balancedLanding':'nea karlsson','50_streetwise':'nea karlsson','56_urbanEvasion':'nea karlsson','15_decisiveStrike':'laurie strode','32_objectOfObsession':'laurie strode','45_soleSurvivor':'laurie strode','08_borrowedTime':'william bill overbeck bill','27_leftBehind':'william bill overbeck bill','54_unbreakable':'william bill overbeck bill','03_alert':'feng min','29_lithe':'feng min','51_technician':'feng min','14_deadHard':'david king','30_noMither':'david king','60_wereGonnaLiveForever':'david king','34_pharmacy':'quentin smith','57_vigil':'quentin smith','58_wakeUp':'quentin smith','18_detectivesHunch':'detective david tapp david tapp tapp','49_stakeOut':'detective david tapp david tapp tapp','52_tenacity':'detective david tapp david tapp tapp','06_boilOver':'kate denson','12_danceWithMe':'kate denson','61_windowsOfOpportunity':'kate denson','04_autodidact':'adam francis','17_deliverance':'adam francis','20_diversion':'adam francis','02_aftercare':'jeff johansen','10_breakdown':'jeff johansen','19_distortion':'jeff johansen','22_headOn':'jane romero','36_poised':'jane romero','46_solidarity':'jane romero'};
const survivorOwnerGroups=[['ashley j williams ash',62],['steve harrington steve',65],['nancy wheeler nancy',68],['yui kimura yui',71],['zarina kassir zarina',74],['cheryl mason cheryl',77],['felix richter felix',80],['elodie rakoto elodie',83],['yun jin lee yun-jin yunjin',86],['jill valentine jill',89],['leon s kennedy leon kennedy leon',92],['mikaela reid mikaela mika',95],['jonah vasquez jonah',98],['yoichi asakawa yoichi',101],['haddie kaur haddie',104],['rebecca chambers rebecca',107],['ada wong ada',110],['vittorio toscano vittorio',113],['renato lyra renato',116],['thalita lyra thalita',119],['gabriel soma gabriel',122],['nicolas cage nicolas nick cage',125],['ellen ripley ripley',128],['alan wake alan',131],['sable ward sable',134],['aestri yazar baermar troupe',137],['lara croft lara',140],['trevor belmont trevor',143],['taurie cain taurie',146],['orela rose orela',149],['rick grimes rick',152],['michonne grimes michonne',155],['vee boonyasak vee',158],['dustin henderson dustin',161],['eleven jane hopper once',164],['kwon tae young kwon tae-young',167],['shane wiigwaas shane',170],['aurora',173]];
const killerOwnerGroups=[['trapper trampero evan macmillan',8],['wraith espectro philip ojomo',7],['hillbilly pueblerino max thompson',53],['nurse enfermera sally smithson',0],['myers shape forma michael myers',54],['hag bruja lisa sherwood',57],['doctor herman carter',10],['huntress cazadora anna',4],['leatherface cannibal canibal bubba',3],['freddy nightmare pesadilla freddy krueger',6],['pig cerda amanda young',18],['clown payaso kenneth chase',2],['spirit espiritu rin yamaoka',11],['legion legion frank julie susie joey',13],['plague plaga adiris',9],['ghost face ghostface danny johnson',57],['demogorgon demo',60],['oni kazan yamaoka',63],['deathslinger arponero caleb quinn',66],['pyramid head executioner verdugo',69],['blight deterioro talbot grimes',72],['twins gemelos charlotte victor',75],['trickster traicionero ji woon hak',78],['nemesis nemesis',81],['cenobite pinhead',84],['artist artista carmina mora',87],['onryo sadako',90],['dredge draga',93],['wesker mastermind',96],['knight caballero tarhos',99],['skull merchant comerciante de calaveras adriana imai',102],['singularity singularidad hux',105],['xenomorph alien',108],['chucky good guy',111],['unknown desconocido',115],['vecna lich liche',118],['dracula dark lord',121],['houndmaster adiestradora canina',124],['ghoul kaneki',127],['animatronic springtrap',130],['krasue',133],['first lich liche',136],['jason slasher',139],['judgment sentencia',142]];
function perkNumber(key){const m=String(key).match(/^(\d+)_/);return m?Number(m[1]):-1}
function ownerFor(item){if(current==='survivor'){if(survivorOwners[item.key])return survivorOwners[item.key];const n=perkNumber(item.key),g=survivorOwnerGroups.find(([,start])=>n>=start&&n<=start+2);return g?g[0]:''}if(current==='killerPerks'){const n=perkNumber(item.key),g=killerOwnerGroups.find(([,start])=>n>=start&&n<=start+2);return g?g[0]:''}return''}
function extraAliases(item){if(current!=='survivor')return'';const n=perkNumber(item.key),a=[];if([95,96,98,101,131].includes(n))a.push('bendicion boon');if(n===14)a.push('chungo dead hard fajador');return a.join(' ')}
function englishFromKey(key){return String(key||'').replace(/^\d+_/,'').replace(/([a-z])([A-Z])/g,'$1 $2')}
function imageFor(item){return item.image?`../${item.image}`:`${sources[current].img}/${item.key}.png`}
function killerSearchAliases(item){if(current!=='killers')return'';const hay=norm(`${item.key} ${item.name}`);const group=killerOwnerGroups.find(([names])=>norm(names).split(' ').some(word=>word.length>3&&hay.includes(word)));return group?group[0]:''}
function searchText(item){return norm(`${item.name||''} ${item.key||''} ${englishFromKey(item.key)} ${item.aliases||''} ${ownerFor(item)} ${killerSearchAliases(item)} ${extraAliases(item)}`)}
function bonusKey(item){return`${current}:${item.key}`}

async function loadTab(key){if(!sources[key])return;current=key;try{const r=await fetch(sources[key].url,{cache:'no-store'});items=await r.json();render()}catch(err){console.error('Roulette catalog:',err);if(grid)grid.innerHTML='<p class="module-status error">No se pudo cargar esta sección.</p>'}}
function render(){if(!grid||!search)return;const words=norm(search.value).split(' ').filter(Boolean);grid.innerHTML='';items.filter(item=>words.every(w=>searchText(item).includes(w))).forEach(item=>{const id=bonusKey(item),value=weights[id]??1,extras=bonusEntries[id]||[],card=document.createElement('article');card.className='weight-card'+(extras.length?' has-bonus':'')+(value===0?' disabled-option':'');card.innerHTML=`<div class="weight-card-info"><img src="${imageFor(item)}" onerror="this.style.visibility='hidden'" alt=""><div class="weight-name">${item.name}</div></div><div class="weight-controls"><button type="button" data-dir="-1">−</button><span class="weight-value">${value}×</span><button type="button" data-dir="1">+</button></div><div class="donor-row"><input class="donor-input" maxlength="32" placeholder="NOMBRE DE QUIEN AGREGA ESTA OPCIÓN" ${value===0?'disabled':''}><button type="button" class="add-entry" ${value===0?'disabled':''}>+ AGREGAR</button></div><div class="bonus-list"></div>`;card.querySelectorAll('.weight-controls button').forEach(b=>b.onclick=()=>{weights[id]=Math.max(0,Math.min(99,(weights[id]??1)+Number(b.dataset.dir)));saveSimulation();render()});const list=card.querySelector('.bonus-list');extras.forEach((name,index)=>{const chip=document.createElement('span');chip.className='bonus-chip';chip.innerHTML=`<span>${name}</span><button type="button" class="remove-bonus" aria-label="Eliminar usuario"><i></i><i></i></button>`;chip.querySelector('button').onclick=()=>{bonusEntries[id].splice(index,1);weights[id]=Math.max(0,(weights[id]??1)-1);saveSimulation();render()};list.appendChild(chip)});const donor=card.querySelector('.donor-input'),add=()=>{const name=donor.value.trim();if(!name)return;(bonusEntries[id]||(bonusEntries[id]=[])).push(name);weights[id]=Math.min(99,(weights[id]??1)+1);saveSimulation();donor.value='';render()};card.querySelector('.add-entry').onclick=add;donor.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();add()}});grid.appendChild(card)})}

function hideAllSections(){if(roulettePanel)roulettePanel.hidden=true;if(tournamentPanel)tournamentPanel.hidden=true;Object.values(streamPanels).forEach(panel=>{if(panel)panel.hidden=true})}
function selectSection(key,{updateHash=true}={}){if(!allPanelKeys.has(key))key='killers';hideAllSections();document.querySelectorAll('.panel-tabs button[data-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.tab===key));if(search)search.value='';if(rouletteTabs.has(key)){if(roulettePanel)roulettePanel.hidden=false;loadTab(key)}else if(key==='tournament'){if(tournamentPanel)tournamentPanel.hidden=false}else if(streamPanels[key]){streamPanels[key].hidden=false}if(updateHash)history.replaceState(null,'',`#${key}`)}
window.SanLeanPanel={selectSection};

document.querySelectorAll('.panel-tabs button[data-tab]').forEach(btn=>btn.addEventListener('click',()=>selectSection(btn.dataset.tab)));
search?.addEventListener('input',render);
const resetModal=document.getElementById('resetModal');
document.getElementById('resetWeights')?.addEventListener('click',()=>{if(resetModal)resetModal.hidden=false});
document.getElementById('cancelReset')?.addEventListener('click',()=>{if(resetModal)resetModal.hidden=true});
document.getElementById('confirmReset')?.addEventListener('click',()=>{Object.keys(weights).filter(k=>k.startsWith(current+':')).forEach(k=>delete weights[k]);Object.keys(bonusEntries).filter(k=>k.startsWith(current+':')).forEach(k=>delete bonusEntries[k]);saveSimulation();if(resetModal)resetModal.hidden=true;render()});
resetModal?.addEventListener('click',e=>{if(e.target===resetModal)resetModal.hidden=true});

window.addEventListener('DOMContentLoaded',()=>{const key=location.hash.replace('#','');selectSection(allPanelKeys.has(key)?key:'killers',{updateHash:false})});
window.addEventListener('hashchange',()=>{const key=location.hash.replace('#','');if(allPanelKeys.has(key))selectSection(key,{updateHash:false})});
