(()=>{
 const $=id=>document.getElementById(id),labels={killers:'KILLERS',survivor:'PERKS DE SUPERVIVIENTE',killerPerks:'PERKS DE KILLER'},catalogs={},safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let activeWorkspace='',selected=null,rules=[],settings=null,editing=null,loadId=0;
 const client=()=>window.sanleanSupabase,tools=()=>window.SanLeanStreamTools,workspace=()=>tools()?.getWorkspace?.(),status=text=>{if($('bitsStatus'))$('bitsStatus').textContent=text};
 const checked=async q=>{const{data,error}=await q;if(error)throw error;return data};
 async function call(action){const session=await window.SanLeanAccount.session();if(!session)throw new Error('Volvé a iniciar sesión.');const r=await fetch(window.SANLEAN_SUPABASE.url+'/functions/v1/stream-bits/'+action,{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({workspaceId:workspace()?.id}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo conectar.');return data}
 async function catalog(kind){if(catalogs[kind])return catalogs[kind];const file={killers:'killers',survivor:'perks-survivor',killerPerks:'perks-killer'}[kind],r=await fetch('../data/'+file+'.json');if(!r.ok)throw new Error('No se pudo cargar el catálogo.');return catalogs[kind]=(await r.json()).filter(x=>!x.emptySlot&&x.key!=='slot_vacio')}
 const picture=(item,kind)=>item.image?'../'+item.image:'../'+(kind==='survivor'?'survivor':'killer')+'/'+item.key+'.png';
 async function search(){const kind=$('bitsKind').value,version=kind;try{const items=await catalog(kind);if($('bitsKind').value!==version)return;const words=window.SanLeanPanel.normalize($('bitsSearch').value).split(' ').filter(Boolean);$('bitsResults').replaceChildren();items.filter(item=>{const text=window.SanLeanPanel.searchText(item,kind)+(item.key==='leatherface'?' buba bubba leatherface':'');return words.every(w=>text.includes(w))}).slice(0,24).forEach(item=>{const button=document.createElement('button');button.type='button';button.className='bits-option';button.innerHTML=`<img src="${safe(picture(item,kind))}" alt="" loading="lazy"><span>${safe(item.name)}</span>`;button.onclick=()=>{selected={...item,kind};$('bitsSelected').textContent=item.name;$('bitsSearch').value='';$('bitsResults').replaceChildren()};$('bitsResults').appendChild(button)})}catch(e){status(e.message)}}
 function list(){const host=$('bitsRules');host.replaceChildren();if(!rules.length){host.textContent='Todavía no agregaste reglas.';return}for(const rule of rules){const row=document.createElement('article');row.className='bits-rule';row.innerHTML=`<div><strong>${rule.bits} BITS → ${safe(rule.item_name)}</strong><p>${labels[rule.kind]} · ${rule.quantity} entrada(s) · ${rule.duration_minutes?rule.duration_minutes+' minutos':'Hasta eliminarlas'} · ${rule.enabled?'ACTIVA':'PAUSADA'}</p></div><div class="module-actions"><button type="button" data-edit>EDITAR</button><button type="button" data-toggle>${rule.enabled?'PAUSAR':'ACTIVAR'}</button><button type="button" data-delete>ELIMINAR</button></div>`;
 row.querySelector('[data-edit]').onclick=()=>{editing=rule.id;selected={key:rule.item_key,name:rule.item_name,image:rule.image,kind:rule.kind};$('bitsAmount').value=rule.bits;$('bitsKind').value=rule.kind;$('bitsQuantity').value=rule.quantity;$('bitsDuration').value=rule.duration_minutes;$('bitsSelected').textContent=rule.item_name;$('bitsSave').textContent='GUARDAR CAMBIOS';$('bitsForm').hidden=false;};
 row.querySelector('[data-toggle]').onclick=async e=>{e.currentTarget.disabled=true;try{await checked(client().from('stream_bits_rules').update({enabled:!rule.enabled}).eq('id',rule.id).eq('workspace_id',activeWorkspace));await refresh(true)}catch(error){status(error.message);e.target.disabled=false}};
 row.querySelector('[data-delete]').onclick=async e=>{e.currentTarget.disabled=true;try{await checked(client().from('stream_bits_rules').delete().eq('id',rule.id).eq('workspace_id',activeWorkspace));await refresh(true)}catch(error){status(error.message);e.target.disabled=false}};host.appendChild(row)}}
 async function refresh(force=false){
  if(!$('bitsOwner')||!client()||!workspace())return;const id=workspace().id;
  $('bitsOwner').hidden=!tools().isOwner();$('bitsPermission').hidden=tools().isOwner();if(!tools().isOwner())return;
  if(activeWorkspace===id&&!force)return;activeWorkspace=id;const version=++loadId;selected=null;editing=null;$('bitsForm').hidden=true;status('Cargando reglas…');
  try{
   let config=await checked(client().from('stream_bits_settings').select('*').eq('workspace_id',id).maybeSingle());
   if(!config)config=await checked(client().from('stream_bits_settings').insert({workspace_id:id}).select('*').single());
   const data=await checked(client().from('stream_bits_rules').select('*').eq('workspace_id',id).order('bits'));
   if(version!==loadId||workspace()?.id!==id)return;settings=config;rules=data||[];$('bitsSound').checked=settings.sound_enabled;list();status('');
   const connection=await call('status');if(workspace()?.id!==id)return;$('bitsConnection').textContent=connection.connected?'TWITCH CONECTADO · BITS ACTIVOS':connection.configured?'Conectá tu canal Twitch para recibir bits.':'Pendiente: registrar y configurar la aplicación Twitch de SanLean. Podés guardar tus reglas y probar la alerta.';$('bitsConnect').disabled=false;$('bitsConnect').textContent='VER CONEXIONES';
   await recent();
  }catch(e){activeWorkspace='';status('No se pudo cargar Bits y alertas. '+e.message)}
 }
 async function recent(){if(!workspace()||!tools().isOwner())return;const id=workspace().id;const rows=await checked(client().from('stream_bits_bonuses').select('id,item_key,kind,donor,expires_at').eq('workspace_id',id).order('created_at',{ascending:false}).limit(100));if(workspace()?.id!==id)return;const host=$('bitsBonuses');host.replaceChildren();for(const row of rows||[]){if(row.expires_at&&Date.parse(row.expires_at)<=Date.now())continue;const items=await catalog(row.kind),item=items.find(x=>x.key===row.item_key),line=document.createElement('div');line.className='bits-bonus';const text=document.createElement('span');text.textContent=`${row.donor} · ${item?.name||row.item_key}`;const button=document.createElement('button');button.type='button';button.textContent='ELIMINAR';button.onclick=async()=>{button.disabled=true;try{await checked(client().from('stream_bits_bonuses').delete().eq('id',row.id).eq('workspace_id',id));await recent()}catch(e){button.disabled=false;status(e.message)}};line.append(text,button);host.appendChild(line)}if(!host.children.length)host.textContent='Sin entradas de bits activas.'}
 async function save(e){e.preventDefault();if(!selected||selected.kind!==$('bitsKind').value){status('Elegí un killer o perk en el buscador.');return}const id=workspace()?.id;if(!id||!tools().isOwner())return;const button=$('bitsSave');button.disabled=true;try{const kind=selected.kind,item=(await catalog(kind)).find(x=>x.key===selected.key);if(!item)throw new Error('Opción inválida.');const value={workspace_id:id,bits:Number($('bitsAmount').value),kind,item_key:item.key,item_name:item.name,image:picture(item,kind),quantity:Number($('bitsQuantity').value),duration_minutes:Number($('bitsDuration').value)};const q=editing?client().from('stream_bits_rules').update(value).eq('id',editing).eq('workspace_id',id):client().from('stream_bits_rules').insert(value);await checked(q);await refresh(true);status('Regla guardada. Se aplica cuando la donación coincide exactamente con esa cantidad de bits.')}catch(error){status(error.code==='23505'?'Ya existe una regla con esa cantidad de bits. Editala o elegí otra cantidad.':error.message)}finally{button.disabled=false}}
 async function mergePool(pool,kind,workspaceId){if(!client()||!workspaceId)return pool;const rows=await checked(client().from('stream_bits_bonuses').select('item_key,donor,expires_at').eq('workspace_id',workspaceId).eq('kind',kind).abortSignal(AbortSignal.timeout(12000)));const map=new Map();for(const b of rows||[]){if(b.expires_at&&Date.parse(b.expires_at)<=Date.now())continue;const a=map.get(b.item_key)||[];a.push(b.donor);map.set(b.item_key,a)}return pool.map(item=>{const baseWeight=item.baseWeight??item.weight,baseDonors=item.baseDonors??item.donors??[],extras=(map.get(item.key)||[]).slice(0,Math.max(0,99-baseWeight));if(baseWeight<=0)return {...item,weight:baseWeight,donors:baseDonors};return {...item,baseWeight,baseDonors,weight:Math.min(99,baseWeight+extras.length),donors:[...baseDonors,...extras].slice(0,98)}})}
 function install(){const host=$('streamBitsPanel');if(!host)return;host.innerHTML=`<div class="stream-module-head"><p class="eyebrow">TWITCH</p><h2>BITS Y ALERTAS</h2><p>Elegí cuántos bits agregan un killer o perk a tus ruletas. Cada regla usa una cantidad exacta.</p></div><p id="bitsPermission" class="module-help">Solo el propietario puede configurar las reglas y conectar Twitch.</p><div id="bitsOwner" hidden><div class="module-box"><p id="bitsConnection">Cargando conexión…</p><div class="module-actions"><button id="bitsConnect" type="button">VER CONEXIONES</button><button id="bitsReload" type="button">ACTUALIZAR</button></div></div><div class="module-box"><div class="module-actions"><button id="bitsAdd" type="button" class="module-primary">+ AGREGAR REGLA</button></div><form id="bitsForm" hidden><div class="bits-fields"><label>CANTIDAD EXACTA DE BITS<input id="bitsAmount" type="number" min="1" max="1000000" step="1" required value="300"></label><label>RULETA<select id="bitsKind"><option value="killers">KILLERS</option><option value="survivor">PERKS DE SUPERVIVIENTE</option><option value="killerPerks">PERKS DE KILLER</option></select></label><label>ENTRADAS QUE AGREGA<input id="bitsQuantity" type="number" min="1" max="20" required value="1"></label><label>DURACIÓN EN MINUTOS · 0 = HASTA ELIMINAR<input id="bitsDuration" type="number" min="0" max="10080" required value="0"></label></div><label>BUSCAR KILLER O PERK<input id="bitsSearch" type="search" placeholder="Nombre, nombre en inglés o personaje…" autocomplete="off"></label><div id="bitsResults" class="bits-results"></div><p id="bitsSelected">Elegí una opción.</p><div class="module-actions"><button id="bitsSave" class="module-primary" type="submit">GUARDAR REGLA</button><button id="bitsCancel" type="button">CANCELAR</button></div></form><div id="bitsRules" class="bits-rules"></div><p class="module-help">Las entradas se suman desde el próximo giro. Se respetan las opciones deshabilitadas y los killers ya usados. Máximo: 99 entradas por opción.</p></div><div class="module-box"><h3>ALERTA EN OBS</h3><p>Agregá esta fuente de navegador una sola vez, por encima de las ruletas, para mostrar y escuchar las donaciones.</p><label class="bits-sound"><input id="bitsSound" type="checkbox" checked> SONIDO DE SORPRESA</label><div class="module-actions"><button id="bitsCopy" type="button">COPIAR URL DE ALERTAS OBS</button><button id="bitsTest" type="button">PROBAR ALERTA</button></div><p class="module-help">Fuente 1920 × 1080. La prueba se abre aparte y no agrega entradas.</p></div><div class="module-box"><h3>ENTRADAS DE BITS ACTIVAS</h3><div id="bitsBonuses"></div></div></div><p id="bitsStatus" class="module-status" role="status"></p>`;
 $('bitsAdd').onclick=()=>{editing=null;selected=null;$('bitsForm').reset();$('bitsSelected').textContent='Elegí una opción.';$('bitsSave').textContent='GUARDAR REGLA';$('bitsForm').hidden=false;search()};$('bitsCancel').onclick=()=>{$('bitsForm').hidden=true};$('bitsSearch').oninput=search;$('bitsKind').onchange=()=>{selected=null;$('bitsSelected').textContent='Elegí una opción.';search()};$('bitsForm').onsubmit=save;$('bitsReload').onclick=()=>refresh(true);$('bitsConnect').onclick=()=>{location.hash='platforms';window.SanLeanUsuarioNavigation?.show('platforms')};
 $('bitsCopy').onclick=async()=>{if(!settings)return;try{await navigator.clipboard.writeText(location.origin+'/Usuario/alertas.html?token='+settings.alert_token);status('URL de alertas copiada.')}catch{status('No se pudo copiar la URL. Permití el acceso al portapapeles y reintentá.')}};
 $('bitsTest').onclick=()=>window.open('./alertas.html?demo=1','_blank','noopener');$('bitsSound').onchange=async e=>{const previous=!e.target.checked;e.target.disabled=true;try{await checked(client().from('stream_bits_settings').update({sound_enabled:e.target.checked}).eq('workspace_id',activeWorkspace))}catch(error){e.target.checked=previous;status(error.message)}finally{e.target.disabled=false}};refresh();
 }
 window.SanLeanBits={mergePool,refresh};window.addEventListener('sanlean:overlays-updated',()=>refresh());window.addEventListener('hashchange',()=>{if(location.hash==='#bits')refresh(true)});window.addEventListener('DOMContentLoaded',install);
})();
