"""Build private, pixel-identical WebP assets; leave public PNGs untouched."""
from pathlib import Path
from PIL import Image
import json

root = Path(__file__).resolve().parents[1]
paths = {x['image'] for x in json.loads((root/'data/killers.json').read_text(encoding='utf-8'))}
for role in ('killer', 'survivor'):
    for item in json.loads((root/f'data/perks-{role}.json').read_text(encoding='utf-8')):
        source = item.get('image', f'{role}/{item["key"]}.png')
        if (root/source).is_file():
            paths.add(source)
mapping, original_bytes, webp_bytes = {}, 0, 0
for source in sorted(paths):
    original = root/source
    target = root/'assets/roulette-private'/Path(source).with_suffix('.webp')
    target.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(original) as image:
        image.save(target, 'WEBP', lossless=True, method=6, exact=True)
        with Image.open(target) as check:
            assert image.convert('RGBA').tobytes() == check.convert('RGBA').tobytes(), source
    original_bytes += original.stat().st_size
    webp_bytes += target.stat().st_size
    mapping['/'+source] = '/'+target.relative_to(root).as_posix()
(root/'js/roulette-image-assets.js').write_text(
    '// Generated by tests/build-roulette-images.py. Private USUARIO/OBS only.\n'
    'window.SanLeanRouletteImageAssets='+json.dumps(mapping, separators=(',', ':'))+';\n', encoding='utf-8')
print(json.dumps(dict(images=len(mapping), original_bytes=original_bytes, webp_bytes=webp_bytes,
                     saved_percent=round((1-webp_bytes/original_bytes)*100, 1))))
