const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const root=path.resolve(__dirname,'..');let fixture=require('./roulette-harness.cjs');
fixture=fixture.replace('</main>','<section id="streamBitsPanel" class="stream-module"></section></main>').replace('</head>','<link rel="stylesheet" href="../css/usuario-bits.css"></head>');
const bitsMock=`<script>
window.SanLeanAccount.session=async()=>({access_token:'fixture-only'});
const bitRows={stream_bits_settings:[],stream_bits_rules:[],stream_bits_bonuses:[]};window.bitRows=bitRows;
window.sanleanSupabase={from(table){if(!bitRows[table])return window.supabase.createClient().from(table);let filters=[],payload=null,operation='read';const q={select(){return q},eq(k,v){filters.push([k,v]);return q},order(){return q},limit(){return q},abortSignal(){return q},insert(v){operation='insert';payload=v;return q},update(v){operation='update';payload=v;return q},delete(){operation='delete';return q},single:async()=>({data:result()[0]}),maybeSingle:async()=>({data:result()[0]||null}),then(resolve,reject){return Promise.resolve({data:result()}).then(resolve,reject)}};function result(){const rows=bitRows[table];if(operation==='insert'){const row={id:crypto.randomUUID(),alert_token:crypto.randomUUID(),sound_enabled:true,enabled:true,...payload};rows.push(row);operation='read';return[row]}const selected=rows.filter(r=>filters.every(([k,v])=>r[k]===v));if(operation==='update')selected.forEach(r=>Object.assign(r,payload));if(operation==='delete')bitRows[table]=rows.filter(r=>!selected.includes(r));operation='read';return selected}return q}};
</script><script src="../js/usuario-bits.js"></script>`;
fixture=fixture.replace('<main ', '<main id="panelView" ').replace('<div id="roulettePanel">','<div class="panel-tabs"><button data-tab="killers">KILLERS</button><button data-tab="bits">BITS</button></div><div id="roulettePanel">');
fixture=fixture.replace('</body>','<script src="../js/usuario-stream-tabs-core.js"></script>'+bitsMock+'</body>');
const server=http.createServer((req,res)=>{try{if(req.url.startsWith('/Usuario/fixture.html')){res.setHeader('Content-Type','text/html');res.end(fixture);return}const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.json':'application/json','.html':'text/html','.png':'image/png','.wav':'audio/wav'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file))}catch{res.writeHead(404);res.end()}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.stack));await page.route('**/*',r=>r.request().url().includes('/stream-bits/status')?r.fulfill({json:{configured:false,connected:false}}):r.request().url().startsWith(base)?r.continue():r.abort());await page.goto(base+'/Usuario/fixture.html#killers');await page.waitForFunction(()=>!document.getElementById('killerModeRemove').disabled);await page.evaluate(()=>window.fixtureDelay=180);
for(let i=0;i<40;i++){const mode=i%2?'Keep':'Remove';await page.locator('#killerMode'+mode).click();assert.equal(await page.locator('#killerMode'+mode).getAttribute('aria-pressed'),'true')}
await page.waitForFunction(()=>document.getElementById('killerRepeatControl').getAttribute('aria-busy')==='false');assert.equal(await page.evaluate(()=>fixtureRows[0].settings.killerRepeatMode),'keep');
await page.evaluate(()=>window.fixtureFail=true);await page.click('#killerModeRemove');await page.waitForFunction(()=>document.getElementById('killerRepeatControl').getAttribute('aria-busy')==='false');assert.equal(await page.locator('#killerModeKeep').getAttribute('aria-pressed'),'true');assert.match(await page.locator('#privateRouletteStatus').textContent(),/prueba/);
await page.evaluate(()=>{window.fixtureFail=false;window.fixtureDelay=0});await page.click('#killerModeRemove');await page.waitForFunction(()=>fixtureRows[0].settings.killerRepeatMode==='remove');assert.equal(await page.locator('#killerModeRemove').textContent(),'ELIMINAR KILLERS');
await page.waitForFunction(()=>document.getElementById('bitsConnection').textContent.includes('Pendiente'));await page.click('[data-section-key="bits"]');assert(await page.locator('#streamBitsPanel').isVisible());await page.click('#bitsAdd');await page.fill('#bitsSearch','buba');await page.waitForTimeout(100);assert.equal(await page.locator('#bitsResults button').count(),1);await page.locator('#bitsResults button').click();await page.click('#bitsSave');await page.waitForFunction(()=>bitRows.stream_bits_rules.length===1);assert.equal(await page.evaluate(()=>bitRows.stream_bits_rules[0].item_key),'leatherface');await page.locator('[data-toggle]').click();await page.waitForFunction(()=>bitRows.stream_bits_rules[0].enabled===false);await page.locator('[data-edit]').click();await page.fill('#bitsAmount','350');await page.click('#bitsSave');await page.waitForFunction(()=>bitRows.stream_bits_rules[0].bits===350);
await page.click('#bitsAdd');await page.selectOption('#bitsKind','survivor');await page.fill('#bitsSearch','me la pela');await page.waitForTimeout(150);assert.equal(await page.locator('#bitsResults button').count(),1);await page.locator('#bitsResults button').click();await page.fill('#bitsAmount','1000');await page.click('#bitsSave');await page.waitForFunction(()=>bitRows.stream_bits_rules.length===2);
const poolChecks=await page.evaluate(async()=>{bitRows.stream_bits_bonuses=[{workspace_id:'w1',kind:'killers',item_key:'leatherface',donor:'DONOR',expires_at:null},{workspace_id:'w1',kind:'killers',item_key:'trapper',donor:'EXPIRED',expires_at:'2020-01-01'},{workspace_id:'other',kind:'killers',item_key:'trapper',donor:'OTHER',expires_at:null}];const pool=[{key:'leatherface',weight:1,donors:[]},{key:'trapper',weight:1,donors:[]},{key:'disabled',weight:0,donors:[]}];const merged=await SanLeanBits.mergePool(pool,'killers','w1');const again=await SanLeanBits.mergePool(merged,'killers','w1');return{merged,again}});assert.equal(poolChecks.merged[0].weight,2);assert.deepEqual(poolChecks.merged,poolChecks.again);assert.equal(poolChecks.merged[1].weight,1);assert.equal(poolChecks.merged[2].weight,0);
const output=path.join(root,'..','roulette-bits-results');fs.mkdirSync(output,{recursive:true});for(const width of [1440,390,320]){await page.setViewportSize({width,height:1000});await page.screenshot({path:path.join(output,'panel-'+width+'.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal overflow '+width)}
await page.goto(base+'/Usuario/overlay.html');await page.evaluate(async()=>{document.getElementById('obsOverlayRoot').classList.remove('obs-hidden');const pool=(await(await fetch('../data/killers.json')).json()).map(x=>({...x,image:'../'+x.image,weight:1}));SanLeanRouletteView.render(document.getElementById('obsStage'),{kind:'roulette_killers',settings:{pool},state:{visible:true,status:'result',items:[{...pool[0],donor:'DONADOR'}]}})});await page.setViewportSize({width:1920,height:1080});await page.waitForTimeout(500);const winner=page.locator('.sl-killer-card.selected');assert.match(await winner.evaluate(c=>getComputedStyle(c).animationName),/sl-killer-float/);assert.match(await page.locator('.sl-killer-card.selected .sl-killer-card-donor').evaluate(c=>getComputedStyle(c).animationName),/sl-donor-pulse/);await page.screenshot({path:path.join(output,'killer-winner.png'),omitBackground:true});
for(const width of [1920,390])for(const kind of ['roulette_killer_perks','roulette_survivor_perks']){await page.setViewportSize({width,height:1080});await page.evaluate(kind=>{SanLeanRouletteView.render(document.getElementById('obsStage'),{kind,state:{visible:true,status:'result',items:[{key:'qa',name:'PERK DE PRUEBA LARGA',image:'../survivor/30_noMither.png',donor:'DONADOR DE PRUEBA'}]}})},kind);const metrics=await page.locator('.sl-roulette-slot').first().evaluate(c=>{const d=c.querySelector('.sl-roulette-donor'),n=c.querySelector('.sl-roulette-name'),f=c.querySelector('.sl-roulette-frame');return{donor:getComputedStyle(d).fontSize,name:getComputedStyle(n).fontSize,above:d.getBoundingClientRect().bottom<=f.getBoundingClientRect().top,color:getComputedStyle(d).color}});assert.equal(metrics.donor,metrics.name);assert(metrics.above);assert.equal(metrics.color,'rgb(255, 0, 60)')}
await page.screenshot({path:path.join(output,'perk-donor.png'),omitBackground:true});await page.goto(base+'/Usuario/alertas.html?demo=1');await page.click('#bitsDemo');assert.equal(await page.locator('#bitsAlert').isVisible(),true);assert.match(await page.locator('#bitsAlert').textContent(),/NO AGREGA ENTRADAS/);await page.screenshot({path:path.join(output,'bits-alert.png'),omitBackground:true});assert.deepEqual(errors,[]);console.log('PASS: 40 rapid switches; failed save rollback and retry; rules add/edit/pause; Buba and ME LA PELA search; bonus expiry/isolation/no double count; 3 widths; persistent killer/donor effects; perk donor position/font; isolated alert demo');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
